import type { ContentPack, ContentLibrary, PackId } from '../types/addOns'
import {
  QUIPLASH_PROMPTS,
  QUIPLASH_FINAL_LASH,
  FIBBAGE_PROMPTS,
  TRIVIA_QUESTIONS,
} from './prompts'

// ── After Dark ────────────────────────────────────────────────────────────────

const afterDarkPack: ContentPack = {
  id: 'after-dark',
  name: 'After Dark',
  tagline: 'For adults only (sort of)',
  description: 'Edgy prompts about dating disasters, workplace awkwardness, and things your mom probably wouldn\'t approve of.',
  priceUsdCents: 999,
  emoji: '🌙',
  accentColor: '#9333ea',
  quiplashPrompts: [
    { id: 'ad-q001', text: 'The worst thing to say on a first date', category: 'after-dark' },
    { id: 'ad-q002', text: 'A red flag in someone\'s dating profile that you somehow ignored', category: 'after-dark' },
    { id: 'ad-q003', text: 'What your ex\'s new partner is definitely like', category: 'after-dark' },
    { id: 'ad-q004', text: 'The worst thing you could accidentally text your boss', category: 'after-dark' },
    { id: 'ad-q005', text: 'Something that\'s technically legal but absolutely should not be', category: 'after-dark' },
    { id: 'ad-q006', text: 'The worst possible thing to overshare on a first date', category: 'after-dark' },
    { id: 'ad-q007', text: 'A dealbreaker that sounds reasonable until you say it out loud', category: 'after-dark' },
    { id: 'ad-q008', text: 'The worst time to run into your ex', category: 'after-dark' },
    { id: 'ad-q009', text: 'What men and women both agree is the worst thing about the other', category: 'after-dark' },
    { id: 'ad-q010', text: 'A pickup line that has definitely never worked', category: 'after-dark' },
    { id: 'ad-q011', text: 'The world\'s worst Netflix and chill setup', category: 'after-dark' },
    { id: 'ad-q012', text: 'Something only your significant other knows about you (and wishes they didn\'t)', category: 'after-dark' },
    { id: 'ad-q013', text: 'The most embarrassing thing that could happen at a work happy hour', category: 'after-dark' },
    { id: 'ad-q014', text: 'A thing adults are WAY too excited about that\'s actually boring', category: 'after-dark' },
    { id: 'ad-q015', text: 'The secret life your coworkers would never suspect you of living', category: 'after-dark' },
    { id: 'ad-q016', text: 'What people are ACTUALLY thinking during a terrible presentation', category: 'after-dark' },
    { id: 'ad-q017', text: 'The unspoken rule of sharing a bathroom with a partner', category: 'after-dark' },
    { id: 'ad-q018', text: 'A "romantic" gesture that is objectively terrifying', category: 'after-dark' },
    { id: 'ad-q019', text: 'The worst thing to discover about someone after you\'ve already moved in together', category: 'after-dark' },
    { id: 'ad-q020', text: 'The most passive-aggressive thing you can do in a relationship', category: 'after-dark' },
    { id: 'ad-q021', text: 'A true crime podcast title about your own mundane life', category: 'after-dark' },
    { id: 'ad-q022', text: 'The thing everyone does but pretends they don\'t', category: 'after-dark' },
    { id: 'ad-q023', text: 'What adults secretly wish they could still get away with', category: 'after-dark' },
    { id: 'ad-q024', text: 'The most suspicious search history item that is totally innocent', category: 'after-dark' },
    { id: 'ad-q025', text: 'A compliment that somehow sounds like an insult', category: 'after-dark' },
    { id: 'ad-q026', text: 'The worst thing to yell during an argument', category: 'after-dark' },
    { id: 'ad-q027', text: 'Something your childhood self would be disappointed to learn about adult life', category: 'after-dark' },
    { id: 'ad-q028', text: 'The most adult thing about being an adult that nobody warned you about', category: 'after-dark' },
    { id: 'ad-q029', text: 'A warning label that should come with a relationship', category: 'after-dark' },
    { id: 'ad-q030', text: 'The worst way to find out you\'ve been cheated on', category: 'after-dark' },
  ],
  quiplashFinalLash: [
    { id: 'ad-ql01', text: 'The most embarrassing thing you\'ve ever done in public that haunts you to this day', category: 'finallash' },
    { id: 'ad-ql02', text: 'The ONE thing that would immediately make you leave a date', category: 'finallash' },
    { id: 'ad-ql03', text: 'A secret you\'d never admit unless you were specifically asked in a party game', category: 'finallash' },
    { id: 'ad-ql04', text: 'What the "real" version of a romantic comedy would look like', category: 'finallash' },
    { id: 'ad-ql05', text: 'The adult version of "I\'m telling mom"', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'Before becoming famous, Channing Tatum worked as a ___', blank: '___', realAnswer: 'male stripper', category: 'celebrity' },
    { text: 'The most common reason people call in sick to work (that isn\'t actually being sick) is ___', blank: '___', realAnswer: 'mental health', category: 'society' },
    { text: 'In ancient Rome, people brushed their teeth with ___', blank: '___', realAnswer: 'urine', category: 'history' },
    { text: 'The average person spends ___ years of their life on the toilet', blank: '___', realAnswer: '3', category: 'records' },
    { text: 'A study found that people who swear a lot tend to be ___', blank: '___', realAnswer: 'more honest', category: 'science' },
    { text: 'In the 1800s, "hysteria" in women was treated by doctors with ___', blank: '___', realAnswer: 'vibrators', category: 'history' },
    { text: 'The average person has ___ serious relationships before finding their long-term partner', blank: '___', realAnswer: '5', category: 'relationships' },
    { text: 'Studies show that couples who laugh together are ___ times more likely to stay together', blank: '___', realAnswer: '40%', category: 'relationships' },
    { text: 'The most common lie told on a first date is ___', blank: '___', realAnswer: '"I love hiking"', category: 'relationships' },
    { text: 'Napoleon Bonaparte was once attacked by ___', blank: '___', realAnswer: 'rabbits', category: 'history' },
    { text: 'Before Viagra was invented, it was originally tested as a treatment for ___', blank: '___', realAnswer: 'chest pain', category: 'science' },
    { text: 'The phrase "rule of thumb" originally referred to the legal right to beat your wife with a stick no wider than ___', blank: '___', realAnswer: 'your thumb', category: 'history' },
    { text: 'A study found that ___ percent of people have checked their phone during sex', blank: '___', realAnswer: '10', category: 'society' },
    { text: 'The most common thing people lie about on dating apps is their ___', blank: '___', realAnswer: 'height', category: 'relationships' },
    { text: 'Ancient Greeks believed a woman could become pregnant by swallowing ___', blank: '___', realAnswer: 'pomegranate seeds', category: 'history' },
    { text: 'A survey found the number one thing couples fight about is ___', blank: '___', realAnswer: 'money', category: 'relationships' },
    { text: 'The world record for the most marriages is held by a man who married ___ times', blank: '___', realAnswer: '29', category: 'records' },
    { text: 'According to studies, the most common time people break up is ___', blank: '___', realAnswer: 'Monday', category: 'relationships' },
    { text: 'The origin of the word "honeymoon" comes from the tradition of drinking ___ for one month after a wedding', blank: '___', realAnswer: 'mead', category: 'history' },
    { text: 'A shocking ___ percent of people admit to snooping through their partner\'s phone', blank: '___', realAnswer: '34', category: 'relationships' },
  ],
  triviaQuestions: [
    {
      id: 'ad-t001',
      text: 'What percentage of people admit to lying on their dating profile?',
      options: ['53%', '12%', '87%', '31%'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t002',
      text: 'According to research, how long does it take for someone to decide if they\'re attracted to you?',
      options: ['Under 1 second', '5 minutes', '30 seconds', '3 minutes'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t003',
      text: 'What was the original purpose of high heels when invented in 17th century France?',
      options: ['For men to look powerful on horseback', 'To show off wealth', 'To keep feet dry in muddy streets', 'For dancing'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'hard',
    },
    {
      id: 'ad-t004',
      text: 'Which of these is the most common reason for divorce globally?',
      options: ['Money issues', 'Cheating', 'Lack of communication', 'Growing apart'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t005',
      text: 'How many times does the average person fall in love in their lifetime?',
      options: ['3 times', '1 time', '7 times', '10 times'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t006',
      text: 'In ancient Egypt, women could do what that was revolutionary for the time?',
      options: ['Own property and divorce their husbands', 'Vote in elections', 'Serve in the army', 'Become pharaohs only'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'medium',
    },
    {
      id: 'ad-t007',
      text: 'What is the most popular "hookup" day of the week according to dating apps?',
      options: ['Sunday', 'Friday', 'Saturday', 'Thursday'],
      correctIndex: 0,
      category: 'society',
      difficulty: 'hard',
    },
    {
      id: 'ad-t008',
      text: 'Which country invented the concept of the "honeymoon"?',
      options: ['Ancient Babylon', 'France', 'Italy', 'England'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'hard',
    },
    {
      id: 'ad-t009',
      text: 'What percentage of married couples say they\'d marry the same person again?',
      options: ['80%', '40%', '60%', '95%'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t010',
      text: 'The term "going steady" originated in which decade?',
      options: ['1950s', '1920s', '1970s', '1930s'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'medium',
    },
    {
      id: 'ad-t011',
      text: 'What hormone is often called the "love hormone"?',
      options: ['Oxytocin', 'Dopamine', 'Serotonin', 'Testosterone'],
      correctIndex: 0,
      category: 'science',
      difficulty: 'easy',
    },
    {
      id: 'ad-t012',
      text: 'How long does the average "honeymoon phase" of a relationship last?',
      options: ['2 years', '6 months', '1 month', '5 years'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t013',
      text: 'Which of these is the #1 topic couples argue about?',
      options: ['Finances', 'In-laws', 'Chores', 'Sex'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t014',
      text: 'What is the average number of sexual partners an American has in a lifetime?',
      options: ['7', '2', '15', '30'],
      correctIndex: 0,
      category: 'society',
      difficulty: 'medium',
    },
    {
      id: 'ad-t015',
      text: 'In which country is it considered rude NOT to burp after a meal?',
      options: ['China', 'Japan', 'India', 'France'],
      correctIndex: 0,
      category: 'culture',
      difficulty: 'easy',
    },
    {
      id: 'ad-t016',
      text: 'What animal mates for life and is often used as a symbol of love?',
      options: ['Albatross', 'Swan', 'Dove', 'Penguin'],
      correctIndex: 0,
      category: 'science',
      difficulty: 'hard',
    },
    {
      id: 'ad-t017',
      text: 'Which celebrity couple\'s breakup was dubbed "The Breakup Heard Around the World"?',
      options: ['Brad Pitt and Jennifer Aniston', 'Kim K and Kanye', 'Justin Bieber and Selena Gomez', 'Beyoncé and Jay-Z'],
      correctIndex: 0,
      category: 'celebrity',
      difficulty: 'easy',
    },
    {
      id: 'ad-t018',
      text: 'What is "benching" in modern dating?',
      options: ['Keeping someone interested without committing', 'Ghosting someone', 'Breaking up over text', 'Dating two people at once'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t019',
      text: 'On average, how many dates does it take before a couple becomes exclusive?',
      options: ['6-8 dates', '1-2 dates', '20+ dates', '3-4 dates'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t020',
      text: 'What fraction of couples who live together eventually get married?',
      options: ['About half', 'Nearly all', 'Less than a quarter', 'About three-quarters'],
      correctIndex: 0,
      category: 'society',
      difficulty: 'medium',
    },
  ],
}

// ── Nerd Pack ─────────────────────────────────────────────────────────────────

const nerdPack: ContentPack = {
  id: 'nerd-pack',
  name: 'Nerd Pack',
  tagline: 'For the chronically online',
  description: 'Prompts for gamers, coders, sci-fi fans, and anyone who\'s ever pulled an all-nighter for non-work reasons.',
  priceUsdCents: 999,
  emoji: '🎮',
  accentColor: '#2563eb',
  quiplashPrompts: [
    { id: 'np-q001', text: 'The worst cheat code in gaming history', category: 'nerd' },
    { id: 'np-q002', text: 'A new error message that would break every programmer\'s spirit', category: 'nerd' },
    { id: 'np-q003', text: 'The most useless superpower in a video game', category: 'nerd' },
    { id: 'np-q004', text: 'What Darth Vader does when he clocks out at the Death Star', category: 'nerd' },
    { id: 'np-q005', text: 'The worst name for a gaming clan', category: 'nerd' },
    { id: 'np-q006', text: 'A tech startup idea that would somehow get $50 million in funding', category: 'nerd' },
    { id: 'np-q007', text: 'What your computer is actually doing when it says "processing"', category: 'nerd' },
    { id: 'np-q008', text: 'The worst way a video game could end', category: 'nerd' },
    { id: 'np-q009', text: 'A rejected Pokémon evolution', category: 'nerd' },
    { id: 'np-q010', text: 'The most devastating thing a game can say at a loading screen', category: 'nerd' },
    { id: 'np-q011', text: 'What the final boss is thinking right before you fight them', category: 'nerd' },
    { id: 'np-q012', text: 'A DLC expansion that nobody asked for', category: 'nerd' },
    { id: 'np-q013', text: 'The worst NPC dialogue you could accidentally trigger', category: 'nerd' },
    { id: 'np-q014', text: 'A programming language invented in hell', category: 'nerd' },
    { id: 'np-q015', text: 'What aliens would say if they hacked Earth\'s internet for one day', category: 'nerd' },
    { id: 'np-q016', text: 'A sci-fi technology that would cause the most immediate chaos', category: 'nerd' },
    { id: 'np-q017', text: 'The worst thing to hear from your dungeon master', category: 'nerd' },
    { id: 'np-q018', text: 'A rejected Marvel superhero name', category: 'nerd' },
    { id: 'np-q019', text: 'The least intimidating villain origin story', category: 'nerd' },
    { id: 'np-q020', text: 'What the characters in a video game do when you close the game', category: 'nerd' },
    { id: 'np-q021', text: 'The tech bro explanation for why they don\'t shower regularly', category: 'nerd' },
    { id: 'np-q022', text: 'An achievement you\'d be embarrassed to show anyone', category: 'nerd' },
    { id: 'np-q023', text: 'The most cursed Star Wars spin-off idea', category: 'nerd' },
    { id: 'np-q024', text: 'What Elon Musk actually types when he says "First principles"', category: 'nerd' },
    { id: 'np-q025', text: 'The worst possible AI assistant name', category: 'nerd' },
    { id: 'np-q026', text: 'A side quest that sounds important but accomplishes nothing', category: 'nerd' },
    { id: 'np-q027', text: 'The real reason every video game protagonist wears the same outfit every day', category: 'nerd' },
    { id: 'np-q028', text: 'An app idea that would get immediately banned from every app store', category: 'nerd' },
    { id: 'np-q029', text: 'The most passive-aggressive code comment you could leave a future developer', category: 'nerd' },
    { id: 'np-q030', text: 'What Gandalf\'s LinkedIn bio says', category: 'nerd' },
  ],
  quiplashFinalLash: [
    { id: 'np-ql01', text: 'The one thing that would instantly break the internet if it happened', category: 'finallash' },
    { id: 'np-ql02', text: 'The worst movie remake that Hollywood hasn\'t made yet (but will)', category: 'finallash' },
    { id: 'np-ql03', text: 'If the internet was shut down for 24 hours, the first thing that would happen', category: 'finallash' },
    { id: 'np-ql04', text: 'A crossover between two franchises that would somehow be the worst thing ever made', category: 'finallash' },
    { id: 'np-ql05', text: 'The video game based on real life that would be completely unplayable', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'The original name for "Google" before it was Google was ___', blank: '___', realAnswer: 'BackRub', category: 'tech' },
    { text: 'The first video game ever sold commercially was ___', blank: '___', realAnswer: 'Computer Space', category: 'gaming' },
    { text: 'Mario\'s last name is ___', blank: '___', realAnswer: 'Mario', category: 'gaming' },
    { text: 'Minecraft\'s original working title during development was ___', blank: '___', realAnswer: 'Cave Game', category: 'gaming' },
    { text: 'The term "bug" in computing comes from an actual ___ found inside a computer in 1947', blank: '___', realAnswer: 'moth', category: 'tech' },
    { text: 'Steve Jobs\' biological father was a ___ immigrant to the US', blank: '___', realAnswer: 'Syrian', category: 'tech' },
    { text: 'The first computer mouse was invented in the 1960s and was made from ___', blank: '___', realAnswer: 'wood', category: 'tech' },
    { text: 'The original Star Wars was rejected by ___ studios before being picked up', blank: '___', realAnswer: '15', category: 'movies' },
    { text: 'The word "robot" was first coined in a 1920 Czech play, where it originally meant ___', blank: '___', realAnswer: 'forced labor', category: 'history' },
    { text: 'The first mobile phone call was made in 1973. The caller\'s first words were: "___"', blank: '___', realAnswer: '"Joel, this is Marty"', category: 'tech' },
    { text: 'NASA\'s Apollo guidance computer had less processing power than a modern ___', blank: '___', realAnswer: 'greeting card', category: 'tech' },
    { text: 'The total weight of all the ants on Earth is roughly equal to the weight of all ___', blank: '___', realAnswer: 'humans', category: 'science' },
    { text: 'The Pac-Man kill screen occurs at level ___', blank: '___', realAnswer: '256', category: 'gaming' },
    { text: 'J.K. Rowling was famously rejected by ___ publishers before Harry Potter was accepted', blank: '___', realAnswer: '12', category: 'books' },
    { text: 'The first email ever sent was sent by Ray Tomlinson — to ___', blank: '___', realAnswer: 'himself', category: 'tech' },
    { text: 'The longest-running video game franchise is ___', blank: '___', realAnswer: 'Space Invaders', category: 'gaming' },
    { text: 'Elon Musk\'s first startup, Zip2, was funded with money he borrowed from ___', blank: '___', realAnswer: 'his father', category: 'tech' },
    { text: 'The term "Wi-Fi" doesn\'t actually stand for anything — it was invented by a marketing firm and originally meant ___', blank: '___', realAnswer: 'nothing', category: 'tech' },
    { text: 'The most downloaded app of all time (as of 2024) is ___', blank: '___', realAnswer: 'TikTok', category: 'tech' },
    { text: 'The first domain name ever registered on the internet was ___', blank: '___', realAnswer: 'Symbolics.com', category: 'tech' },
  ],
  triviaQuestions: [
    {
      id: 'np-t001',
      text: 'What does "HTTP" stand for?',
      options: ['HyperText Transfer Protocol', 'High Tech Transfer Protocol', 'Hyper Transfer Typing Protocol', 'Home Text Transfer Page'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t002',
      text: 'In what year was the first iPhone released?',
      options: ['2007', '2004', '2009', '2005'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t003',
      text: 'Which programming language was created by Guido van Rossum?',
      options: ['Python', 'Java', 'Ruby', 'C++'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t004',
      text: 'What is the highest possible score in the original Pac-Man arcade game?',
      options: ['3,333,360', '999,999', '1,000,000', '9,999,999'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'hard',
    },
    {
      id: 'np-t005',
      text: 'Which video game franchise has sold the most copies of all time?',
      options: ['Mario', 'Call of Duty', 'Pokémon', 'Minecraft'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'medium',
    },
    {
      id: 'np-t006',
      text: 'What does "GPU" stand for?',
      options: ['Graphics Processing Unit', 'General Processing Unit', 'Game Power Unit', 'Graphical Program Utility'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t007',
      text: 'In "Star Wars," what species is Yoda?',
      options: ['Unknown — never named in canon', 'Jedi', 'Yaddle', 'Whills'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'medium',
    },
    {
      id: 'np-t008',
      text: 'What is the name of the AI in 2001: A Space Odyssey?',
      options: ['HAL 9000', 'JARVIS', 'SKYNET', 'WALL-E'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'np-t009',
      text: 'Which company made the first commercially successful smartphone?',
      options: ['BlackBerry', 'Nokia', 'Apple', 'Samsung'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'medium',
    },
    {
      id: 'np-t010',
      text: 'In Pokémon, what type is Gengar?',
      options: ['Ghost/Poison', 'Dark/Ghost', 'Ghost/Psychic', 'Normal/Ghost'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'easy',
    },
    {
      id: 'np-t011',
      text: 'What does "RAM" stand for?',
      options: ['Random Access Memory', 'Read And Modify', 'Rapid Access Module', 'Runtime Application Memory'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t012',
      text: 'Who created the World Wide Web?',
      options: ['Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Vint Cerf'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t013',
      text: 'In "The Matrix," what color is the pill Neo takes to see the truth?',
      options: ['Red', 'Blue', 'Green', 'Black'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'np-t014',
      text: 'What is the best-selling video game of all time (single title, not franchise)?',
      options: ['Minecraft', 'Tetris', 'GTA V', 'Wii Sports'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'medium',
    },
    {
      id: 'np-t015',
      text: 'What does "USB" stand for?',
      options: ['Universal Serial Bus', 'Universal System Bridge', 'Unified Serial Bus', 'Universal Storage Buffer'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t016',
      text: 'Which sci-fi show has the line "Live long and prosper"?',
      options: ['Star Trek', 'Star Wars', 'Battlestar Galactica', 'Lost in Space'],
      correctIndex: 0,
      category: 'tv',
      difficulty: 'easy',
    },
    {
      id: 'np-t017',
      text: 'What year did the first "Legend of Zelda" game release?',
      options: ['1986', '1980', '1990', '1983'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'medium',
    },
    {
      id: 'np-t018',
      text: 'What number system do computers use at the most fundamental level?',
      options: ['Binary (base 2)', 'Hexadecimal (base 16)', 'Decimal (base 10)', 'Octal (base 8)'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t019',
      text: 'Which company developed the Android operating system before Google bought it?',
      options: ['Android Inc.', 'HTC', 'Motorola', 'Samsung'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'hard',
    },
    {
      id: 'np-t020',
      text: 'In gaming, what does "FPS" stand for?',
      options: ['First Person Shooter', 'Frames Per Second', 'Both are correct', 'Fight Play Simulator'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'easy',
    },
  ],
}

// ── World Tour ────────────────────────────────────────────────────────────────

const worldTourPack: ContentPack = {
  id: 'world-tour',
  name: 'World Tour',
  tagline: 'Passports not required',
  description: 'Geography, culture, food, and travel disasters from every corner of the planet.',
  priceUsdCents: 999,
  emoji: '🌍',
  accentColor: '#059669',
  quiplashPrompts: [
    { id: 'wt-q001', text: 'The weirdest law that actually exists in another country', category: 'world' },
    { id: 'wt-q002', text: 'The worst thing you could accidentally do in a foreign culture', category: 'world' },
    { id: 'wt-q003', text: 'A travel guidebook title for the world\'s most dangerous vacation spot', category: 'world' },
    { id: 'wt-q004', text: 'The thing Americans do that confuses every other country', category: 'world' },
    { id: 'wt-q005', text: 'A new cuisine you\'d find at a restaurant called "Global Chaos Kitchen"', category: 'world' },
    { id: 'wt-q006', text: 'The worst travel souvenir you could bring back for someone', category: 'world' },
    { id: 'wt-q007', text: 'What would happen if the world suddenly spoke only one language', category: 'world' },
    { id: 'wt-q008', text: 'The most suspicious thing to declare at customs', category: 'world' },
    { id: 'wt-q009', text: 'A hotel sign that would make you immediately check out', category: 'world' },
    { id: 'wt-q010', text: 'The worst seatmate you could have on a 12-hour international flight', category: 'world' },
    { id: 'wt-q011', text: 'A dish that sounds amazing until you ask what\'s in it', category: 'food' },
    { id: 'wt-q012', text: 'The least helpful phrase in a foreign language phrasebook', category: 'world' },
    { id: 'wt-q013', text: 'What a "local" tourist trap looks like in your hometown', category: 'world' },
    { id: 'wt-q014', text: 'The world\'s most passive-aggressive border sign', category: 'world' },
    { id: 'wt-q015', text: 'A cultural taboo you definitely committed without knowing it', category: 'world' },
    { id: 'wt-q016', text: 'The worst country to get lost in with no phone and no map', category: 'world' },
    { id: 'wt-q017', text: 'What Airbnb hosts are actually doing during your stay', category: 'world' },
    { id: 'wt-q018', text: 'A new national holiday for the world\'s most chaotic country', category: 'world' },
    { id: 'wt-q019', text: 'The food combination that proves two countries should never have met', category: 'food' },
    { id: 'wt-q020', text: 'What every country secretly thinks about every other country', category: 'world' },
    { id: 'wt-q021', text: 'A warning sign that should be outside every airport in the world', category: 'world' },
    { id: 'wt-q022', text: 'The most passive-aggressive thing a GPS can say in a foreign city', category: 'world' },
    { id: 'wt-q023', text: 'An international dish that would end trade relations if served at a summit', category: 'food' },
    { id: 'wt-q024', text: 'The world\'s worst travel influencer caption', category: 'world' },
    { id: 'wt-q025', text: 'A new world wonder that nobody asked for', category: 'world' },
    { id: 'wt-q026', text: 'What the Eiffel Tower is whispering to tourists', category: 'world' },
    { id: 'wt-q027', text: 'The real reason time zones were invented', category: 'world' },
    { id: 'wt-q028', text: 'A travel ban that would genuinely improve the world', category: 'world' },
    { id: 'wt-q029', text: 'The most dramatic thing that ever happened at a Waffle House (international edition)', category: 'food' },
    { id: 'wt-q030', text: 'A country that should definitely have its own reality TV show', category: 'world' },
  ],
  quiplashFinalLash: [
    { id: 'wt-ql01', text: 'If you could only eat food from ONE country for the rest of your life, which cuisine would absolutely break you by month 3', category: 'finallash' },
    { id: 'wt-ql02', text: 'The one universal law all countries should immediately agree on', category: 'finallash' },
    { id: 'wt-ql03', text: 'The country that would survive a zombie apocalypse longest and why', category: 'finallash' },
    { id: 'wt-ql04', text: 'What aliens would put in their guide book about Earth under "Things to Avoid"', category: 'finallash' },
    { id: 'wt-ql05', text: 'The most chaotic city in the world to try and find a parking spot in', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'In Denmark, you must name your baby from an approved list of ___ names', blank: '___', realAnswer: '7,000', category: 'culture' },
    { text: 'The most expensive spice in the world, by weight, is ___', blank: '___', realAnswer: 'saffron', category: 'food' },
    { text: 'Finland has won the most World Sauna Championships. The record is ___ minutes inside a sauna above 110°C', blank: '___', realAnswer: '3.5', category: 'records' },
    { text: 'The country that consumes the most chocolate per person per year is ___', blank: '___', realAnswer: 'Switzerland', category: 'food' },
    { text: 'In Japan, there is a town officially named ___', blank: '___', realAnswer: 'Obama', category: 'geography' },
    { text: 'The world\'s shortest international bridge connects the US to Canada and is only ___ feet long', blank: '___', realAnswer: '18', category: 'geography' },
    { text: 'Iceland has no ___, making it one of the safest countries in the world', blank: '___', realAnswer: 'army', category: 'culture' },
    { text: 'The country with the most languages spoken within its borders is ___', blank: '___', realAnswer: 'Papua New Guinea', category: 'culture' },
    { text: 'In Norway, it is illegal to ___', blank: '___', realAnswer: 'spay a female dog', category: 'laws' },
    { text: 'France is the world\'s most visited tourist destination, with over ___ million visitors per year', blank: '___', realAnswer: '90', category: 'travel' },
    { text: 'The original kimchi in Korea was NOT spicy — it only became spicy after ___ was introduced', blank: '___', realAnswer: 'chili peppers from the Americas', category: 'food' },
    { text: 'Canada owns roughly ___% of the world\'s freshwater', blank: '___', realAnswer: '20', category: 'geography' },
    { text: 'Russia is so large that it spans ___ time zones', blank: '___', realAnswer: '11', category: 'geography' },
    { text: 'The world\'s busiest airport (by passengers) is located in ___', blank: '___', realAnswer: 'Atlanta', category: 'travel' },
    { text: 'Pizza was invented in ___, but Americans eat 3 billion pizzas per year', blank: '___', realAnswer: 'Naples, Italy', category: 'food' },
    { text: 'Australia has a government-designated zone called the ___', blank: '___', realAnswer: 'Animal Exclusion Zone', category: 'culture' },
    { text: 'The longest place name in the world is a hill in New Zealand that has ___ letters', blank: '___', realAnswer: '85', category: 'geography' },
    { text: 'Singapore once banned ___ for several decades', blank: '___', realAnswer: 'chewing gum', category: 'laws' },
    { text: 'The smallest country in the world by area is ___, which fits inside a single city', blank: '___', realAnswer: 'Vatican City', category: 'geography' },
    { text: 'Brazil is home to ___ of the world\'s plant and animal species', blank: '___', realAnswer: '10%', category: 'science' },
  ],
  triviaQuestions: [
    {
      id: 'wt-t001',
      text: 'What is the most spoken language in the world by native speakers?',
      options: ['Mandarin Chinese', 'English', 'Spanish', 'Hindi'],
      correctIndex: 0,
      category: 'language',
      difficulty: 'easy',
    },
    {
      id: 'wt-t002',
      text: 'Which country has the largest population in the world?',
      options: ['India', 'China', 'USA', 'Indonesia'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t003',
      text: 'What is the capital city of Australia?',
      options: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'medium',
    },
    {
      id: 'wt-t004',
      text: 'In which country was pizza invented?',
      options: ['Italy', 'Greece', 'France', 'Turkey'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'easy',
    },
    {
      id: 'wt-t005',
      text: 'Which river is the longest in the world?',
      options: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t006',
      text: 'What country has the most pyramids in the world?',
      options: ['Sudan', 'Egypt', 'Mexico', 'Peru'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'hard',
    },
    {
      id: 'wt-t007',
      text: 'What is the national dish of Japan?',
      options: ['Curry rice', 'Sushi', 'Ramen', 'Tempura'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'medium',
    },
    {
      id: 'wt-t008',
      text: 'Which continent has the most countries?',
      options: ['Africa', 'Asia', 'Europe', 'South America'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t009',
      text: 'What is the smallest country in the world?',
      options: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t010',
      text: 'Which country invented sushi?',
      options: ['Japan', 'China', 'Korea', 'Thailand'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'easy',
    },
    {
      id: 'wt-t011',
      text: 'In what country would you find the ancient ruins of Machu Picchu?',
      options: ['Peru', 'Mexico', 'Bolivia', 'Chile'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t012',
      text: 'What is the world\'s spiciest chili pepper?',
      options: ['Carolina Reaper', 'Ghost Pepper', 'Habanero', 'Trinidad Moruga Scorpion'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'medium',
    },
    {
      id: 'wt-t013',
      text: 'Which country has the most UNESCO World Heritage Sites?',
      options: ['Italy', 'China', 'Spain', 'France'],
      correctIndex: 0,
      category: 'culture',
      difficulty: 'hard',
    },
    {
      id: 'wt-t014',
      text: 'What is the official language of Brazil?',
      options: ['Portuguese', 'Spanish', 'English', 'Brazilian'],
      correctIndex: 0,
      category: 'language',
      difficulty: 'easy',
    },
    {
      id: 'wt-t015',
      text: 'The Sahara Desert is located on which continent?',
      options: ['Africa', 'Asia', 'South America', 'Australia'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t016',
      text: 'Which city is known as "The City of Light"?',
      options: ['Paris', 'Rome', 'London', 'Vienna'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t017',
      text: 'What is the most popular street food in the world by volume?',
      options: ['Satay / skewered meat', 'Hot dogs', 'Tacos', 'Falafel'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'hard',
    },
    {
      id: 'wt-t018',
      text: 'In Japan, what does bowing deeply show?',
      options: ['Great respect', 'Agreement', 'Apology', 'Greeting only'],
      correctIndex: 0,
      category: 'culture',
      difficulty: 'easy',
    },
    {
      id: 'wt-t019',
      text: 'Which country has the longest coastline in the world?',
      options: ['Canada', 'Australia', 'Russia', 'Norway'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'medium',
    },
    {
      id: 'wt-t020',
      text: 'The Great Wall of China was primarily built to protect against invasions from which direction?',
      options: ['North', 'East', 'South', 'West'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'easy',
    },
  ],
}

// ── Pack Registry ─────────────────────────────────────────────────────────────

export const CONTENT_PACKS: Record<PackId, ContentPack> = {
  'after-dark': afterDarkPack,
  'nerd-pack': nerdPack,
  'world-tour': worldTourPack,
}

export const PACK_ORDER: PackId[] = ['after-dark', 'nerd-pack', 'world-tour']

export function buildContentLibrary(activeAddOnIds: string[]): ContentLibrary {
  const base: ContentLibrary = {
    quiplashPrompts: QUIPLASH_PROMPTS.filter(p => p.category !== 'finallash'),
    quiplashFinalLash: [...QUIPLASH_FINAL_LASH],
    fibbagePrompts: [...FIBBAGE_PROMPTS],
    triviaQuestions: [...TRIVIA_QUESTIONS],
  }

  for (const id of activeAddOnIds) {
    const pack = CONTENT_PACKS[id as PackId]
    if (!pack) continue
    base.quiplashPrompts = [...base.quiplashPrompts, ...pack.quiplashPrompts]
    base.quiplashFinalLash = [...base.quiplashFinalLash, ...pack.quiplashFinalLash]
    base.fibbagePrompts = [...base.fibbagePrompts, ...pack.fibbagePrompts]
    base.triviaQuestions = [...base.triviaQuestions, ...pack.triviaQuestions]
  }

  return base
}
