import type { ContentPack, ContentLibrary, PackId } from '../types/addOns'
import type { SketchBluffPromptDef } from '../types/sketchbluff'
import {
  QUIPLASH_PROMPTS,
  QUIPLASH_FINAL_LASH,
  FIBBAGE_PROMPTS,
  TRIVIA_QUESTIONS,
  SKETCHBLUFF_PROMPTS,
} from './prompts'

// ── After Dark ────────────────────────────────────────────────────────────────

const afterDarkPack: ContentPack = {
  id: 'after-dark',
  name: 'After Dark',
  tagline: 'For adults only (sort of)',
  description: 'Edgy prompts about dating disasters, workplace awkwardness, and things your mom probably wouldn\'t approve of.',
  priceUsdCents: 999,
  emoji: '🌙',
  accentColor: '#9333ea',
  quiplashPrompts: [
    { id: 'ad-q001', text: 'The worst thing to say on a first date', category: 'after-dark' },
    { id: 'ad-q002', text: 'A red flag in someone\'s dating profile that you somehow ignored', category: 'after-dark' },
    { id: 'ad-q003', text: 'What your ex\'s new partner is definitely like', category: 'after-dark' },
    { id: 'ad-q004', text: 'The worst thing you could accidentally text your boss', category: 'after-dark' },
    { id: 'ad-q005', text: 'Something that\'s technically legal but absolutely should not be', category: 'after-dark' },
    { id: 'ad-q006', text: 'The worst possible thing to overshare on a first date', category: 'after-dark' },
    { id: 'ad-q007', text: 'A dealbreaker that sounds reasonable until you say it out loud', category: 'after-dark' },
    { id: 'ad-q008', text: 'The worst time to run into your ex', category: 'after-dark' },
    { id: 'ad-q009', text: 'What men and women both agree is the worst thing about the other', category: 'after-dark' },
    { id: 'ad-q010', text: 'A pickup line that has definitely never worked', category: 'after-dark' },
    { id: 'ad-q011', text: 'The world\'s worst Netflix and chill setup', category: 'after-dark' },
    { id: 'ad-q012', text: 'Something only your significant other knows about you (and wishes they didn\'t)', category: 'after-dark' },
    { id: 'ad-q013', text: 'The most embarrassing thing that could happen at a work happy hour', category: 'after-dark' },
    { id: 'ad-q014', text: 'A thing adults are WAY too excited about that\'s actually boring', category: 'after-dark' },
    { id: 'ad-q015', text: 'The secret life your coworkers would never suspect you of living', category: 'after-dark' },
    { id: 'ad-q016', text: 'What people are ACTUALLY thinking during a terrible presentation', category: 'after-dark' },
    { id: 'ad-q017', text: 'The unspoken rule of sharing a bathroom with a partner', category: 'after-dark' },
    { id: 'ad-q018', text: 'A "romantic" gesture that is objectively terrifying', category: 'after-dark' },
    { id: 'ad-q019', text: 'The worst thing to discover about someone after you\'ve already moved in together', category: 'after-dark' },
    { id: 'ad-q020', text: 'The most passive-aggressive thing you can do in a relationship', category: 'after-dark' },
    { id: 'ad-q021', text: 'A true crime podcast title about your own mundane life', category: 'after-dark' },
    { id: 'ad-q022', text: 'The thing everyone does but pretends they don\'t', category: 'after-dark' },
    { id: 'ad-q023', text: 'What adults secretly wish they could still get away with', category: 'after-dark' },
    { id: 'ad-q024', text: 'The most suspicious search history item that is totally innocent', category: 'after-dark' },
    { id: 'ad-q025', text: 'A compliment that somehow sounds like an insult', category: 'after-dark' },
    { id: 'ad-q026', text: 'The worst thing to yell during an argument', category: 'after-dark' },
    { id: 'ad-q027', text: 'Something your childhood self would be disappointed to learn about adult life', category: 'after-dark' },
    { id: 'ad-q028', text: 'The most adult thing about being an adult that nobody warned you about', category: 'after-dark' },
    { id: 'ad-q029', text: 'A warning label that should come with a relationship', category: 'after-dark' },
    { id: 'ad-q030', text: 'The worst way to find out you\'ve been cheated on', category: 'after-dark' },
  ],
  quiplashFinalLash: [
    { id: 'ad-ql01', text: 'The most embarrassing thing you\'ve ever done in public that haunts you to this day', category: 'finallash' },
    { id: 'ad-ql02', text: 'The ONE thing that would immediately make you leave a date', category: 'finallash' },
    { id: 'ad-ql03', text: 'A secret you\'d never admit unless you were specifically asked in a party game', category: 'finallash' },
    { id: 'ad-ql04', text: 'What the "real" version of a romantic comedy would look like', category: 'finallash' },
    { id: 'ad-ql05', text: 'The adult version of "I\'m telling mom"', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'Before becoming famous, Channing Tatum worked as a ___', blank: '___', realAnswer: 'male stripper', category: 'celebrity' },
    { text: 'The most common reason people call in sick to work (that isn\'t actually being sick) is ___', blank: '___', realAnswer: 'mental health', category: 'society' },
    { text: 'In ancient Rome, people brushed their teeth with ___', blank: '___', realAnswer: 'urine', category: 'history' },
    { text: 'The average person spends ___ years of their life on the toilet', blank: '___', realAnswer: '3', category: 'records' },
    { text: 'A study found that people who swear a lot tend to be ___', blank: '___', realAnswer: 'more honest', category: 'science' },
    { text: 'In the 1800s, "hysteria" in women was treated by doctors with ___', blank: '___', realAnswer: 'vibrators', category: 'history' },
    { text: 'The average person has ___ serious relationships before finding their long-term partner', blank: '___', realAnswer: '5', category: 'relationships' },
    { text: 'Studies show that couples who laugh together are ___ times more likely to stay together', blank: '___', realAnswer: '40%', category: 'relationships' },
    { text: 'The most common lie told on a first date is ___', blank: '___', realAnswer: '"I love hiking"', category: 'relationships' },
    { text: 'Napoleon Bonaparte was once attacked by ___', blank: '___', realAnswer: 'rabbits', category: 'history' },
    { text: 'Before Viagra was invented, it was originally tested as a treatment for ___', blank: '___', realAnswer: 'chest pain', category: 'science' },
    { text: 'The phrase "rule of thumb" originally referred to the legal right to beat your wife with a stick no wider than ___', blank: '___', realAnswer: 'your thumb', category: 'history' },
    { text: 'A study found that ___ percent of people have checked their phone during sex', blank: '___', realAnswer: '10', category: 'society' },
    { text: 'The most common thing people lie about on dating apps is their ___', blank: '___', realAnswer: 'height', category: 'relationships' },
    { text: 'Ancient Greeks believed a woman could become pregnant by swallowing ___', blank: '___', realAnswer: 'pomegranate seeds', category: 'history' },
    { text: 'A survey found the number one thing couples fight about is ___', blank: '___', realAnswer: 'money', category: 'relationships' },
    { text: 'The world record for the most marriages is held by a man who married ___ times', blank: '___', realAnswer: '29', category: 'records' },
    { text: 'According to studies, the most common time people break up is ___', blank: '___', realAnswer: 'Monday', category: 'relationships' },
    { text: 'The origin of the word "honeymoon" comes from the tradition of drinking ___ for one month after a wedding', blank: '___', realAnswer: 'mead', category: 'history' },
    { text: 'A shocking ___ percent of people admit to snooping through their partner\'s phone', blank: '___', realAnswer: '34', category: 'relationships' },
  ],
  triviaQuestions: [
    {
      id: 'ad-t001',
      text: 'What percentage of people admit to lying on their dating profile?',
      options: ['53%', '12%', '87%', '31%'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t002',
      text: 'According to research, how long does it take for someone to decide if they\'re attracted to you?',
      options: ['Under 1 second', '5 minutes', '30 seconds', '3 minutes'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t003',
      text: 'What was the original purpose of high heels when invented in 17th century France?',
      options: ['For men to look powerful on horseback', 'To show off wealth', 'To keep feet dry in muddy streets', 'For dancing'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'hard',
    },
    {
      id: 'ad-t004',
      text: 'Which of these is the most common reason for divorce globally?',
      options: ['Money issues', 'Cheating', 'Lack of communication', 'Growing apart'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t005',
      text: 'How many times does the average person fall in love in their lifetime?',
      options: ['3 times', '1 time', '7 times', '10 times'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t006',
      text: 'In ancient Egypt, women could do what that was revolutionary for the time?',
      options: ['Own property and divorce their husbands', 'Vote in elections', 'Serve in the army', 'Become pharaohs only'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'medium',
    },
    {
      id: 'ad-t007',
      text: 'What is the most popular "hookup" day of the week according to dating apps?',
      options: ['Sunday', 'Friday', 'Saturday', 'Thursday'],
      correctIndex: 0,
      category: 'society',
      difficulty: 'hard',
    },
    {
      id: 'ad-t008',
      text: 'Which country invented the concept of the "honeymoon"?',
      options: ['Ancient Babylon', 'France', 'Italy', 'England'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'hard',
    },
    {
      id: 'ad-t009',
      text: 'What percentage of married couples say they\'d marry the same person again?',
      options: ['80%', '40%', '60%', '95%'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t010',
      text: 'The term "going steady" originated in which decade?',
      options: ['1950s', '1920s', '1970s', '1930s'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'medium',
    },
    {
      id: 'ad-t011',
      text: 'What hormone is often called the "love hormone"?',
      options: ['Oxytocin', 'Dopamine', 'Serotonin', 'Testosterone'],
      correctIndex: 0,
      category: 'science',
      difficulty: 'easy',
    },
    {
      id: 'ad-t012',
      text: 'How long does the average "honeymoon phase" of a relationship last?',
      options: ['2 years', '6 months', '1 month', '5 years'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t013',
      text: 'Which of these is the #1 topic couples argue about?',
      options: ['Finances', 'In-laws', 'Chores', 'Sex'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t014',
      text: 'What is the average number of sexual partners an American has in a lifetime?',
      options: ['7', '2', '15', '30'],
      correctIndex: 0,
      category: 'society',
      difficulty: 'medium',
    },
    {
      id: 'ad-t015',
      text: 'In which country is it considered rude NOT to burp after a meal?',
      options: ['China', 'Japan', 'India', 'France'],
      correctIndex: 0,
      category: 'culture',
      difficulty: 'easy',
    },
    {
      id: 'ad-t016',
      text: 'What animal mates for life and is often used as a symbol of love?',
      options: ['Albatross', 'Swan', 'Dove', 'Penguin'],
      correctIndex: 0,
      category: 'science',
      difficulty: 'hard',
    },
    {
      id: 'ad-t017',
      text: 'Which celebrity couple\'s breakup was dubbed "The Breakup Heard Around the World"?',
      options: ['Brad Pitt and Jennifer Aniston', 'Kim K and Kanye', 'Justin Bieber and Selena Gomez', 'Beyoncé and Jay-Z'],
      correctIndex: 0,
      category: 'celebrity',
      difficulty: 'easy',
    },
    {
      id: 'ad-t018',
      text: 'What is "benching" in modern dating?',
      options: ['Keeping someone interested without committing', 'Ghosting someone', 'Breaking up over text', 'Dating two people at once'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'easy',
    },
    {
      id: 'ad-t019',
      text: 'On average, how many dates does it take before a couple becomes exclusive?',
      options: ['6-8 dates', '1-2 dates', '20+ dates', '3-4 dates'],
      correctIndex: 0,
      category: 'relationships',
      difficulty: 'medium',
    },
    {
      id: 'ad-t020',
      text: 'What fraction of couples who live together eventually get married?',
      options: ['About half', 'Nearly all', 'Less than a quarter', 'About three-quarters'],
      correctIndex: 0,
      category: 'society',
      difficulty: 'medium',
    },
  ],
}

// ── Nerd Pack ─────────────────────────────────────────────────────────────────

const nerdPack: ContentPack = {
  id: 'nerd-pack',
  name: 'Nerd Pack',
  tagline: 'For the chronically online',
  description: 'Prompts for gamers, coders, sci-fi fans, and anyone who\'s ever pulled an all-nighter for non-work reasons.',
  priceUsdCents: 999,
  emoji: '🎮',
  accentColor: '#2563eb',
  quiplashPrompts: [
    { id: 'np-q001', text: 'The worst cheat code in gaming history', category: 'nerd' },
    { id: 'np-q002', text: 'A new error message that would break every programmer\'s spirit', category: 'nerd' },
    { id: 'np-q003', text: 'The most useless superpower in a video game', category: 'nerd' },
    { id: 'np-q004', text: 'What Darth Vader does when he clocks out at the Death Star', category: 'nerd' },
    { id: 'np-q005', text: 'The worst name for a gaming clan', category: 'nerd' },
    { id: 'np-q006', text: 'A tech startup idea that would somehow get $50 million in funding', category: 'nerd' },
    { id: 'np-q007', text: 'What your computer is actually doing when it says "processing"', category: 'nerd' },
    { id: 'np-q008', text: 'The worst way a video game could end', category: 'nerd' },
    { id: 'np-q009', text: 'A rejected Pokémon evolution', category: 'nerd' },
    { id: 'np-q010', text: 'The most devastating thing a game can say at a loading screen', category: 'nerd' },
    { id: 'np-q011', text: 'What the final boss is thinking right before you fight them', category: 'nerd' },
    { id: 'np-q012', text: 'A DLC expansion that nobody asked for', category: 'nerd' },
    { id: 'np-q013', text: 'The worst NPC dialogue you could accidentally trigger', category: 'nerd' },
    { id: 'np-q014', text: 'A programming language invented in hell', category: 'nerd' },
    { id: 'np-q015', text: 'What aliens would say if they hacked Earth\'s internet for one day', category: 'nerd' },
    { id: 'np-q016', text: 'A sci-fi technology that would cause the most immediate chaos', category: 'nerd' },
    { id: 'np-q017', text: 'The worst thing to hear from your dungeon master', category: 'nerd' },
    { id: 'np-q018', text: 'A rejected Marvel superhero name', category: 'nerd' },
    { id: 'np-q019', text: 'The least intimidating villain origin story', category: 'nerd' },
    { id: 'np-q020', text: 'What the characters in a video game do when you close the game', category: 'nerd' },
    { id: 'np-q021', text: 'The tech bro explanation for why they don\'t shower regularly', category: 'nerd' },
    { id: 'np-q022', text: 'An achievement you\'d be embarrassed to show anyone', category: 'nerd' },
    { id: 'np-q023', text: 'The most cursed Star Wars spin-off idea', category: 'nerd' },
    { id: 'np-q024', text: 'What Elon Musk actually types when he says "First principles"', category: 'nerd' },
    { id: 'np-q025', text: 'The worst possible AI assistant name', category: 'nerd' },
    { id: 'np-q026', text: 'A side quest that sounds important but accomplishes nothing', category: 'nerd' },
    { id: 'np-q027', text: 'The real reason every video game protagonist wears the same outfit every day', category: 'nerd' },
    { id: 'np-q028', text: 'An app idea that would get immediately banned from every app store', category: 'nerd' },
    { id: 'np-q029', text: 'The most passive-aggressive code comment you could leave a future developer', category: 'nerd' },
    { id: 'np-q030', text: 'What Gandalf\'s LinkedIn bio says', category: 'nerd' },
  ],
  quiplashFinalLash: [
    { id: 'np-ql01', text: 'The one thing that would instantly break the internet if it happened', category: 'finallash' },
    { id: 'np-ql02', text: 'The worst movie remake that Hollywood hasn\'t made yet (but will)', category: 'finallash' },
    { id: 'np-ql03', text: 'If the internet was shut down for 24 hours, the first thing that would happen', category: 'finallash' },
    { id: 'np-ql04', text: 'A crossover between two franchises that would somehow be the worst thing ever made', category: 'finallash' },
    { id: 'np-ql05', text: 'The video game based on real life that would be completely unplayable', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'The original name for "Google" before it was Google was ___', blank: '___', realAnswer: 'BackRub', category: 'tech' },
    { text: 'The first video game ever sold commercially was ___', blank: '___', realAnswer: 'Computer Space', category: 'gaming' },
    { text: 'Mario\'s last name is ___', blank: '___', realAnswer: 'Mario', category: 'gaming' },
    { text: 'Minecraft\'s original working title during development was ___', blank: '___', realAnswer: 'Cave Game', category: 'gaming' },
    { text: 'The term "bug" in computing comes from an actual ___ found inside a computer in 1947', blank: '___', realAnswer: 'moth', category: 'tech' },
    { text: 'Steve Jobs\' biological father was a ___ immigrant to the US', blank: '___', realAnswer: 'Syrian', category: 'tech' },
    { text: 'The first computer mouse was invented in the 1960s and was made from ___', blank: '___', realAnswer: 'wood', category: 'tech' },
    { text: 'The original Star Wars was rejected by ___ studios before being picked up', blank: '___', realAnswer: '15', category: 'movies' },
    { text: 'The word "robot" was first coined in a 1920 Czech play, where it originally meant ___', blank: '___', realAnswer: 'forced labor', category: 'history' },
    { text: 'The first mobile phone call was made in 1973. The caller\'s first words were: "___"', blank: '___', realAnswer: '"Joel, this is Marty"', category: 'tech' },
    { text: 'NASA\'s Apollo guidance computer had less processing power than a modern ___', blank: '___', realAnswer: 'greeting card', category: 'tech' },
    { text: 'The total weight of all the ants on Earth is roughly equal to the weight of all ___', blank: '___', realAnswer: 'humans', category: 'science' },
    { text: 'The Pac-Man kill screen occurs at level ___', blank: '___', realAnswer: '256', category: 'gaming' },
    { text: 'J.K. Rowling was famously rejected by ___ publishers before Harry Potter was accepted', blank: '___', realAnswer: '12', category: 'books' },
    { text: 'The first email ever sent was sent by Ray Tomlinson — to ___', blank: '___', realAnswer: 'himself', category: 'tech' },
    { text: 'The longest-running video game franchise is ___', blank: '___', realAnswer: 'Space Invaders', category: 'gaming' },
    { text: 'Elon Musk\'s first startup, Zip2, was funded with money he borrowed from ___', blank: '___', realAnswer: 'his father', category: 'tech' },
    { text: 'The term "Wi-Fi" doesn\'t actually stand for anything — it was invented by a marketing firm and originally meant ___', blank: '___', realAnswer: 'nothing', category: 'tech' },
    { text: 'The most downloaded app of all time (as of 2024) is ___', blank: '___', realAnswer: 'TikTok', category: 'tech' },
    { text: 'The first domain name ever registered on the internet was ___', blank: '___', realAnswer: 'Symbolics.com', category: 'tech' },
  ],
  triviaQuestions: [
    {
      id: 'np-t001',
      text: 'What does "HTTP" stand for?',
      options: ['HyperText Transfer Protocol', 'High Tech Transfer Protocol', 'Hyper Transfer Typing Protocol', 'Home Text Transfer Page'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t002',
      text: 'In what year was the first iPhone released?',
      options: ['2007', '2004', '2009', '2005'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t003',
      text: 'Which programming language was created by Guido van Rossum?',
      options: ['Python', 'Java', 'Ruby', 'C++'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t004',
      text: 'What is the highest possible score in the original Pac-Man arcade game?',
      options: ['3,333,360', '999,999', '1,000,000', '9,999,999'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'hard',
    },
    {
      id: 'np-t005',
      text: 'Which video game franchise has sold the most copies of all time?',
      options: ['Mario', 'Call of Duty', 'Pokémon', 'Minecraft'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'medium',
    },
    {
      id: 'np-t006',
      text: 'What does "GPU" stand for?',
      options: ['Graphics Processing Unit', 'General Processing Unit', 'Game Power Unit', 'Graphical Program Utility'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t007',
      text: 'In "Star Wars," what species is Yoda?',
      options: ['Unknown — never named in canon', 'Jedi', 'Yaddle', 'Whills'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'medium',
    },
    {
      id: 'np-t008',
      text: 'What is the name of the AI in 2001: A Space Odyssey?',
      options: ['HAL 9000', 'JARVIS', 'SKYNET', 'WALL-E'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'np-t009',
      text: 'Which company made the first commercially successful smartphone?',
      options: ['BlackBerry', 'Nokia', 'Apple', 'Samsung'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'medium',
    },
    {
      id: 'np-t010',
      text: 'In Pokémon, what type is Gengar?',
      options: ['Ghost/Poison', 'Dark/Ghost', 'Ghost/Psychic', 'Normal/Ghost'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'easy',
    },
    {
      id: 'np-t011',
      text: 'What does "RAM" stand for?',
      options: ['Random Access Memory', 'Read And Modify', 'Rapid Access Module', 'Runtime Application Memory'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t012',
      text: 'Who created the World Wide Web?',
      options: ['Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Vint Cerf'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t013',
      text: 'In "The Matrix," what color is the pill Neo takes to see the truth?',
      options: ['Red', 'Blue', 'Green', 'Black'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'np-t014',
      text: 'What is the best-selling video game of all time (single title, not franchise)?',
      options: ['Minecraft', 'Tetris', 'GTA V', 'Wii Sports'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'medium',
    },
    {
      id: 'np-t015',
      text: 'What does "USB" stand for?',
      options: ['Universal Serial Bus', 'Universal System Bridge', 'Unified Serial Bus', 'Universal Storage Buffer'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t016',
      text: 'Which sci-fi show has the line "Live long and prosper"?',
      options: ['Star Trek', 'Star Wars', 'Battlestar Galactica', 'Lost in Space'],
      correctIndex: 0,
      category: 'tv',
      difficulty: 'easy',
    },
    {
      id: 'np-t017',
      text: 'What year did the first "Legend of Zelda" game release?',
      options: ['1986', '1980', '1990', '1983'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'medium',
    },
    {
      id: 'np-t018',
      text: 'What number system do computers use at the most fundamental level?',
      options: ['Binary (base 2)', 'Hexadecimal (base 16)', 'Decimal (base 10)', 'Octal (base 8)'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'easy',
    },
    {
      id: 'np-t019',
      text: 'Which company developed the Android operating system before Google bought it?',
      options: ['Android Inc.', 'HTC', 'Motorola', 'Samsung'],
      correctIndex: 0,
      category: 'tech',
      difficulty: 'hard',
    },
    {
      id: 'np-t020',
      text: 'In gaming, what does "FPS" stand for?',
      options: ['First Person Shooter', 'Frames Per Second', 'Both are correct', 'Fight Play Simulator'],
      correctIndex: 0,
      category: 'gaming',
      difficulty: 'easy',
    },
  ],
}

// ── World Tour ────────────────────────────────────────────────────────────────

const worldTourPack: ContentPack = {
  id: 'world-tour',
  name: 'World Tour',
  tagline: 'Passports not required',
  description: 'Geography, culture, food, and travel disasters from every corner of the planet.',
  priceUsdCents: 999,
  emoji: '🌍',
  accentColor: '#059669',
  quiplashPrompts: [
    { id: 'wt-q001', text: 'The weirdest law that actually exists in another country', category: 'world' },
    { id: 'wt-q002', text: 'The worst thing you could accidentally do in a foreign culture', category: 'world' },
    { id: 'wt-q003', text: 'A travel guidebook title for the world\'s most dangerous vacation spot', category: 'world' },
    { id: 'wt-q004', text: 'The thing Americans do that confuses every other country', category: 'world' },
    { id: 'wt-q005', text: 'A new cuisine you\'d find at a restaurant called "Global Chaos Kitchen"', category: 'world' },
    { id: 'wt-q006', text: 'The worst travel souvenir you could bring back for someone', category: 'world' },
    { id: 'wt-q007', text: 'What would happen if the world suddenly spoke only one language', category: 'world' },
    { id: 'wt-q008', text: 'The most suspicious thing to declare at customs', category: 'world' },
    { id: 'wt-q009', text: 'A hotel sign that would make you immediately check out', category: 'world' },
    { id: 'wt-q010', text: 'The worst seatmate you could have on a 12-hour international flight', category: 'world' },
    { id: 'wt-q011', text: 'A dish that sounds amazing until you ask what\'s in it', category: 'food' },
    { id: 'wt-q012', text: 'The least helpful phrase in a foreign language phrasebook', category: 'world' },
    { id: 'wt-q013', text: 'What a "local" tourist trap looks like in your hometown', category: 'world' },
    { id: 'wt-q014', text: 'The world\'s most passive-aggressive border sign', category: 'world' },
    { id: 'wt-q015', text: 'A cultural taboo you definitely committed without knowing it', category: 'world' },
    { id: 'wt-q016', text: 'The worst country to get lost in with no phone and no map', category: 'world' },
    { id: 'wt-q017', text: 'What Airbnb hosts are actually doing during your stay', category: 'world' },
    { id: 'wt-q018', text: 'A new national holiday for the world\'s most chaotic country', category: 'world' },
    { id: 'wt-q019', text: 'The food combination that proves two countries should never have met', category: 'food' },
    { id: 'wt-q020', text: 'What every country secretly thinks about every other country', category: 'world' },
    { id: 'wt-q021', text: 'A warning sign that should be outside every airport in the world', category: 'world' },
    { id: 'wt-q022', text: 'The most passive-aggressive thing a GPS can say in a foreign city', category: 'world' },
    { id: 'wt-q023', text: 'An international dish that would end trade relations if served at a summit', category: 'food' },
    { id: 'wt-q024', text: 'The world\'s worst travel influencer caption', category: 'world' },
    { id: 'wt-q025', text: 'A new world wonder that nobody asked for', category: 'world' },
    { id: 'wt-q026', text: 'What the Eiffel Tower is whispering to tourists', category: 'world' },
    { id: 'wt-q027', text: 'The real reason time zones were invented', category: 'world' },
    { id: 'wt-q028', text: 'A travel ban that would genuinely improve the world', category: 'world' },
    { id: 'wt-q029', text: 'The most dramatic thing that ever happened at a Waffle House (international edition)', category: 'food' },
    { id: 'wt-q030', text: 'A country that should definitely have its own reality TV show', category: 'world' },
  ],
  quiplashFinalLash: [
    { id: 'wt-ql01', text: 'If you could only eat food from ONE country for the rest of your life, which cuisine would absolutely break you by month 3', category: 'finallash' },
    { id: 'wt-ql02', text: 'The one universal law all countries should immediately agree on', category: 'finallash' },
    { id: 'wt-ql03', text: 'The country that would survive a zombie apocalypse longest and why', category: 'finallash' },
    { id: 'wt-ql04', text: 'What aliens would put in their guide book about Earth under "Things to Avoid"', category: 'finallash' },
    { id: 'wt-ql05', text: 'The most chaotic city in the world to try and find a parking spot in', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'In Denmark, you must name your baby from an approved list of ___ names', blank: '___', realAnswer: '7,000', category: 'culture' },
    { text: 'The most expensive spice in the world, by weight, is ___', blank: '___', realAnswer: 'saffron', category: 'food' },
    { text: 'Finland has won the most World Sauna Championships. The record is ___ minutes inside a sauna above 110°C', blank: '___', realAnswer: '3.5', category: 'records' },
    { text: 'The country that consumes the most chocolate per person per year is ___', blank: '___', realAnswer: 'Switzerland', category: 'food' },
    { text: 'In Japan, there is a town officially named ___', blank: '___', realAnswer: 'Obama', category: 'geography' },
    { text: 'The world\'s shortest international bridge connects the US to Canada and is only ___ feet long', blank: '___', realAnswer: '18', category: 'geography' },
    { text: 'Iceland has no ___, making it one of the safest countries in the world', blank: '___', realAnswer: 'army', category: 'culture' },
    { text: 'The country with the most languages spoken within its borders is ___', blank: '___', realAnswer: 'Papua New Guinea', category: 'culture' },
    { text: 'In Norway, it is illegal to ___', blank: '___', realAnswer: 'spay a female dog', category: 'laws' },
    { text: 'France is the world\'s most visited tourist destination, with over ___ million visitors per year', blank: '___', realAnswer: '90', category: 'travel' },
    { text: 'The original kimchi in Korea was NOT spicy — it only became spicy after ___ was introduced', blank: '___', realAnswer: 'chili peppers from the Americas', category: 'food' },
    { text: 'Canada owns roughly ___% of the world\'s freshwater', blank: '___', realAnswer: '20', category: 'geography' },
    { text: 'Russia is so large that it spans ___ time zones', blank: '___', realAnswer: '11', category: 'geography' },
    { text: 'The world\'s busiest airport (by passengers) is located in ___', blank: '___', realAnswer: 'Atlanta', category: 'travel' },
    { text: 'Pizza was invented in ___, but Americans eat 3 billion pizzas per year', blank: '___', realAnswer: 'Naples, Italy', category: 'food' },
    { text: 'Australia has a government-designated zone called the ___', blank: '___', realAnswer: 'Animal Exclusion Zone', category: 'culture' },
    { text: 'The longest place name in the world is a hill in New Zealand that has ___ letters', blank: '___', realAnswer: '85', category: 'geography' },
    { text: 'Singapore once banned ___ for several decades', blank: '___', realAnswer: 'chewing gum', category: 'laws' },
    { text: 'The smallest country in the world by area is ___, which fits inside a single city', blank: '___', realAnswer: 'Vatican City', category: 'geography' },
    { text: 'Brazil is home to ___ of the world\'s plant and animal species', blank: '___', realAnswer: '10%', category: 'science' },
  ],
  triviaQuestions: [
    {
      id: 'wt-t001',
      text: 'What is the most spoken language in the world by native speakers?',
      options: ['Mandarin Chinese', 'English', 'Spanish', 'Hindi'],
      correctIndex: 0,
      category: 'language',
      difficulty: 'easy',
    },
    {
      id: 'wt-t002',
      text: 'Which country has the largest population in the world?',
      options: ['India', 'China', 'USA', 'Indonesia'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t003',
      text: 'What is the capital city of Australia?',
      options: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'medium',
    },
    {
      id: 'wt-t004',
      text: 'In which country was pizza invented?',
      options: ['Italy', 'Greece', 'France', 'Turkey'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'easy',
    },
    {
      id: 'wt-t005',
      text: 'Which river is the longest in the world?',
      options: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t006',
      text: 'What country has the most pyramids in the world?',
      options: ['Sudan', 'Egypt', 'Mexico', 'Peru'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'hard',
    },
    {
      id: 'wt-t007',
      text: 'What is the national dish of Japan?',
      options: ['Curry rice', 'Sushi', 'Ramen', 'Tempura'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'medium',
    },
    {
      id: 'wt-t008',
      text: 'Which continent has the most countries?',
      options: ['Africa', 'Asia', 'Europe', 'South America'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t009',
      text: 'What is the smallest country in the world?',
      options: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t010',
      text: 'Which country invented sushi?',
      options: ['Japan', 'China', 'Korea', 'Thailand'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'easy',
    },
    {
      id: 'wt-t011',
      text: 'In what country would you find the ancient ruins of Machu Picchu?',
      options: ['Peru', 'Mexico', 'Bolivia', 'Chile'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t012',
      text: 'What is the world\'s spiciest chili pepper?',
      options: ['Carolina Reaper', 'Ghost Pepper', 'Habanero', 'Trinidad Moruga Scorpion'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'medium',
    },
    {
      id: 'wt-t013',
      text: 'Which country has the most UNESCO World Heritage Sites?',
      options: ['Italy', 'China', 'Spain', 'France'],
      correctIndex: 0,
      category: 'culture',
      difficulty: 'hard',
    },
    {
      id: 'wt-t014',
      text: 'What is the official language of Brazil?',
      options: ['Portuguese', 'Spanish', 'English', 'Brazilian'],
      correctIndex: 0,
      category: 'language',
      difficulty: 'easy',
    },
    {
      id: 'wt-t015',
      text: 'The Sahara Desert is located on which continent?',
      options: ['Africa', 'Asia', 'South America', 'Australia'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t016',
      text: 'Which city is known as "The City of Light"?',
      options: ['Paris', 'Rome', 'London', 'Vienna'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'easy',
    },
    {
      id: 'wt-t017',
      text: 'What is the most popular street food in the world by volume?',
      options: ['Satay / skewered meat', 'Hot dogs', 'Tacos', 'Falafel'],
      correctIndex: 0,
      category: 'food',
      difficulty: 'hard',
    },
    {
      id: 'wt-t018',
      text: 'In Japan, what does bowing deeply show?',
      options: ['Great respect', 'Agreement', 'Apology', 'Greeting only'],
      correctIndex: 0,
      category: 'culture',
      difficulty: 'easy',
    },
    {
      id: 'wt-t019',
      text: 'Which country has the longest coastline in the world?',
      options: ['Canada', 'Australia', 'Russia', 'Norway'],
      correctIndex: 0,
      category: 'geography',
      difficulty: 'medium',
    },
    {
      id: 'wt-t020',
      text: 'The Great Wall of China was primarily built to protect against invasions from which direction?',
      options: ['North', 'East', 'South', 'West'],
      correctIndex: 0,
      category: 'history',
      difficulty: 'easy',
    },
  ],
}

// ── Sketch Bluff Pack ─────────────────────────────────────────────────────────

const sketchBluffPack: ContentPack = {
  id: 'sketch-bluff',
  name: 'Sketch Bluff Pack',
  tagline: 'Weirder prompts, wilder drawings',
  description: 'More absurd drawing prompts for Sketch Bluff, plus art-themed Quiplash, Fibbage, and Trivia.',
  priceUsdCents: 999,
  emoji: '🎨',
  accentColor: '#ea580c',
  sketchbluffPrompts: [
    { id: 'sbp001', text: 'A penguin explaining capitalism', category: 'characters' },
    { id: 'sbp002', text: 'A haunted dentist\'s office', category: 'spooky' },
    { id: 'sbp003', text: 'A secret agent who is also a golden retriever', category: 'animals' },
    { id: 'sbp004', text: 'Two clouds arguing over nothing', category: 'weather' },
    { id: 'sbp005', text: 'A submarine running a lemonade stand', category: 'vehicles' },
    { id: 'sbp006', text: 'A skeleton who just found out they are a skeleton', category: 'spooky' },
    { id: 'sbp007', text: 'A tiny knight fighting a regular-sized sandwich', category: 'food' },
    { id: 'sbp008', text: 'A giraffe trying to fit into a phone booth', category: 'animals' },
    { id: 'sbp009', text: 'A haunted washing machine', category: 'objects' },
    { id: 'sbp010', text: 'A dragon who is afraid of fire', category: 'fantasy' },
    { id: 'sbp011', text: 'A fish applying for a library card', category: 'animals' },
    { id: 'sbp012', text: 'A robot learning to be romantic', category: 'tech' },
    { id: 'sbp013', text: 'A cloud that produces confetti instead of rain', category: 'weather' },
    { id: 'sbp014', text: 'A retired superhero doing yard work', category: 'superhero' },
    { id: 'sbp015', text: 'A ghost trying to use a touchscreen', category: 'spooky' },
    { id: 'sbp016', text: 'A snail in a serious hurry', category: 'animals' },
    { id: 'sbp017', text: 'An umbrella that refuses to open', category: 'objects' },
    { id: 'sbp018', text: 'A time machine stuck in rush hour traffic', category: 'sci-fi' },
    { id: 'sbp019', text: 'An ant operating a forklift', category: 'animals' },
    { id: 'sbp020', text: 'A bored astronaut doing household chores on the moon', category: 'space' },
    { id: 'sbp021', text: 'A tree filing its taxes', category: 'nature' },
    { id: 'sbp022', text: 'A couch that has seen far too much', category: 'objects' },
    { id: 'sbp023', text: 'A pigeon who sincerely believes it is a hawk', category: 'animals' },
    { id: 'sbp024', text: 'A nervous volcano on a first date', category: 'nature' },
    { id: 'sbp025', text: 'An octopus trying to shake everyone\'s hand at once', category: 'animals' },
    { id: 'sbp026', text: 'A sunflower winning a trophy', category: 'nature' },
    { id: 'sbp027', text: 'A haunted selfie stick', category: 'tech' },
    { id: 'sbp028', text: 'A refrigerator on vacation at the beach', category: 'objects' },
    { id: 'sbp029', text: 'A cat explaining quantum physics on a whiteboard', category: 'animals' },
    { id: 'sbp030', text: 'A wizard\'s absolute worst spell', category: 'fantasy' },
  ] as SketchBluffPromptDef[],
  quiplashPrompts: [
    { id: 'sb-q001', text: 'The worst thing to draw when someone asks for a "quick sketch"', category: 'art' },
    { id: 'sb-q002', text: 'A modern art piece that fools absolutely nobody', category: 'art' },
    { id: 'sb-q003', text: 'What the Mona Lisa is actually smiling about', category: 'art' },
    { id: 'sb-q004', text: 'A rejected name for a very famous painting', category: 'art' },
    { id: 'sb-q005', text: 'The world\'s most passive-aggressive graffiti tag', category: 'art' },
    { id: 'sb-q006', text: 'What happens at an art museum after the lights go off', category: 'art' },
    { id: 'sb-q007', text: 'A new art movement that gets banned immediately', category: 'art' },
    { id: 'sb-q008', text: 'The least inspiring thing a life drawing teacher could say', category: 'art' },
    { id: 'sb-q009', text: 'What your work doodles secretly reveal about you', category: 'art' },
    { id: 'sb-q010', text: 'A title for a sculpture that is literally just a pile of rocks', category: 'art' },
    { id: 'sb-q011', text: 'The worst thing to graffiti over a masterpiece', category: 'art' },
    { id: 'sb-q012', text: 'What the Sistine Chapel ceiling SHOULD have been', category: 'art' },
    { id: 'sb-q013', text: 'An art class critique that would end someone\'s career', category: 'art' },
    { id: 'sb-q014', text: 'A museum exhibit that would clear a room in under 10 seconds', category: 'art' },
    { id: 'sb-q015', text: 'What Picasso was REALLY trying to say', category: 'art' },
    { id: 'sb-q016', text: 'The worst tattoo concept you have ever been asked to explain', category: 'art' },
    { id: 'sb-q017', text: 'A gallery description for the most boring piece of art ever made', category: 'art' },
    { id: 'sb-q018', text: 'The most pretentious thing you can say about a stick figure', category: 'art' },
    { id: 'sb-q019', text: 'What "abstract expressionism" actually means to someone who doesn\'t know', category: 'art' },
    { id: 'sb-q020', text: 'A new color that humanity absolutely does not need', category: 'art' },
    { id: 'sb-q021', text: 'What Bob Ross was REALLY painting over on that canvas', category: 'art' },
    { id: 'sb-q022', text: 'An art school graduation speech that makes everyone switch majors', category: 'art' },
    { id: 'sb-q023', text: 'The most useless artist\'s tool ever invented', category: 'art' },
    { id: 'sb-q024', text: 'What the world\'s worst art heist target is', category: 'art' },
    { id: 'sb-q025', text: 'A new emoji that would immediately cause chaos', category: 'art' },
    { id: 'sb-q026', text: 'The rejected 8th Wonder of the World', category: 'art' },
    { id: 'sb-q027', text: 'What street artists write in the fine print of their murals', category: 'art' },
    { id: 'sb-q028', text: 'The worst thing you could accidentally draw in Pictionary', category: 'art' },
    { id: 'sb-q029', text: 'A painting title that accidentally becomes a hit movie', category: 'art' },
    { id: 'sb-q030', text: 'The thing you drew as a kid that your parents displayed on the fridge ironically', category: 'art' },
  ],
  quiplashFinalLash: [
    { id: 'sb-ql01', text: 'If you had to draw a masterpiece using only MS Paint in 30 seconds, what would you title it', category: 'finallash' },
    { id: 'sb-ql02', text: 'The art movement that perfectly captures how 2024 felt', category: 'finallash' },
    { id: 'sb-ql03', text: 'What a time capsule archaeologist in year 3000 would think our cave drawings meant', category: 'finallash' },
    { id: 'sb-ql04', text: 'The thing you tried to draw once that made you give up art forever', category: 'finallash' },
    { id: 'sb-ql05', text: 'If your soul had a color and texture, what unholy art supply describes it', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'The most expensive painting ever sold fetched ___ at auction', blank: '___', realAnswer: '$450.3 million', category: 'art' },
    { text: 'Van Gogh only sold ___ painting during his entire lifetime', blank: '___', realAnswer: 'one', category: 'art' },
    { text: 'Pablo Picasso\'s full legal name has ___ words in it', blank: '___', realAnswer: '23', category: 'art' },
    { text: 'The cave paintings at Lascaux, France have remained vivid for ___', blank: '___', realAnswer: '17,000 years', category: 'history' },
    { text: 'The Mona Lisa has no ___', blank: '___', realAnswer: 'eyebrows', category: 'art' },
    { text: 'Salvador Dalí used to pay restaurant bills with ___', blank: '___', realAnswer: 'drawings on the back of checks', category: 'art' },
    { text: 'Andy Warhol earned his living drawing ___ before he became famous', blank: '___', realAnswer: 'shoes for a fashion magazine', category: 'art' },
    { text: 'Michelangelo painted the Sistine Chapel while standing, not ___', blank: '___', realAnswer: 'lying on his back', category: 'art' },
    { text: 'Jackson Pollock\'s drip technique was inspired by ___', blank: '___', realAnswer: 'Native American sand painting', category: 'art' },
    { text: 'Frida Kahlo began painting seriously after ___', blank: '___', realAnswer: 'a near-fatal bus accident left her bedridden', category: 'art' },
    { text: 'A painting made by a 4-year-old chimpanzee sold at auction for over ___', blank: '___', realAnswer: '$25,000', category: 'art' },
    { text: 'The pencil was invented ___ years before the eraser', blank: '___', realAnswer: '200', category: 'history' },
    { text: 'The Louvre receives more annual visitors than the entire population of ___', blank: '___', realAnswer: 'Australia', category: 'art' },
    { text: 'Henri Matisse switched from studying law to painting after ___', blank: '___', realAnswer: 'a bout of appendicitis left him bedridden', category: 'art' },
    { text: 'The Blue Period in Picasso\'s art was triggered by ___', blank: '___', realAnswer: 'his close friend\'s suicide', category: 'art' },
    { text: 'The original color of the Eiffel Tower (now gray) was ___', blank: '___', realAnswer: 'reddish-brown', category: 'history' },
    { text: 'The world\'s smallest painting fits on a ___', blank: '___', realAnswer: 'grain of rice', category: 'art' },
    { text: 'Banksy\'s real identity is still ___', blank: '___', realAnswer: 'officially unknown', category: 'art' },
    { text: 'The world\'s largest painting by a single artist covers ___ square feet', blank: '___', realAnswer: '17,000', category: 'art' },
    { text: 'In the original Pictionary rules, you are not allowed to ___', blank: '___', realAnswer: 'use numbers or letters in your drawing', category: 'games' },
  ],
  triviaQuestions: [
    {
      id: 'sb-t001',
      text: 'Who painted the Mona Lisa?',
      options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Caravaggio'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t002',
      text: 'What art movement is Jackson Pollock associated with?',
      options: ['Abstract Expressionism', 'Surrealism', 'Pop Art', 'Cubism'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'medium',
    },
    {
      id: 'sb-t003',
      text: 'Who painted "Starry Night"?',
      options: ['Vincent van Gogh', 'Claude Monet', 'Paul Gauguin', 'Georges Seurat'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t004',
      text: 'What is a "triptych"?',
      options: ['A work of art in three panels', 'A painting technique', 'A type of brush', 'A 3D sculpture'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'medium',
    },
    {
      id: 'sb-t005',
      text: 'Who created "The Persistence of Memory" (the melting clocks)?',
      options: ['Salvador Dalí', 'Pablo Picasso', 'René Magritte', 'Frida Kahlo'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t006',
      text: 'What is the technique of applying very thick paint to a canvas called?',
      options: ['Impasto', 'Chiaroscuro', 'Sfumato', 'Tenebrism'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'hard',
    },
    {
      id: 'sb-t007',
      text: 'Who created the famous marble statue of David?',
      options: ['Michelangelo', 'Leonardo da Vinci', 'Donatello', 'Bernini'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t008',
      text: 'Banksy is primarily known for what type of art?',
      options: ['Street art / graffiti', 'Watercolor', 'Digital art', 'Sculpture'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t009',
      text: '"The Scream" was painted by which artist?',
      options: ['Edvard Munch', 'Gustav Klimt', 'Wassily Kandinsky', 'Paul Klee'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'medium',
    },
    {
      id: 'sb-t010',
      text: 'What material are most modern pencils actually made of (not lead)?',
      options: ['Graphite', 'Lead', 'Carbon', 'Charcoal'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t011',
      text: 'Which of these is NOT a primary color in traditional (pigment) art?',
      options: ['Green', 'Blue', 'Red', 'Yellow'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t012',
      text: 'How long did it take Michelangelo to paint the Sistine Chapel ceiling?',
      options: ['4 years', '1 year', '10 years', '7 years'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'medium',
    },
    {
      id: 'sb-t013',
      text: 'What does "chiaroscuro" refer to in painting?',
      options: ['The contrast of light and dark shadow', 'A type of Italian marble', 'A painting medium', 'A brush technique'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'hard',
    },
    {
      id: 'sb-t014',
      text: 'The art style where tiny dots of color are used to form images is called?',
      options: ['Pointillism', 'Impressionism', 'Fauvism', 'Cubism'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'medium',
    },
    {
      id: 'sb-t015',
      text: 'Which primary color is used in LIGHT (additive) mixing but NOT in pigment mixing?',
      options: ['Green', 'Yellow', 'Orange', 'Purple'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'hard',
    },
    {
      id: 'sb-t016',
      text: 'What are the colored dot patterns in Roy Lichtenstein\'s pop art called?',
      options: ['Ben-Day dots', 'Pointillist dots', 'Halftone dots', 'Stipple marks'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'hard',
    },
    {
      id: 'sb-t017',
      text: 'What is the most visited art museum in the world?',
      options: ['The Louvre', 'The British Museum', 'The Metropolitan Museum', 'The Uffizi'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
    {
      id: 'sb-t018',
      text: 'Who founded the Bauhaus school of art and design?',
      options: ['Walter Gropius', 'Ludwig Mies van der Rohe', 'Marcel Breuer', 'Paul Klee'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'hard',
    },
    {
      id: 'sb-t019',
      text: 'Impressionism as a style was originally intended as?',
      options: ['An insult by an art critic', 'A compliment from a rival', 'The artists\' own name for the style', 'A gallery marketing term'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'medium',
    },
    {
      id: 'sb-t020',
      text: 'What body part did Van Gogh famously cut off?',
      options: ['Part of his left ear', 'His pinky finger', 'His entire right ear', 'The tip of his nose'],
      correctIndex: 0,
      category: 'art',
      difficulty: 'easy',
    },
  ],
}

// ── Pop Culture Pack ──────────────────────────────────────────────────────────

const popCulturePack: ContentPack = {
  id: 'pop-culture',
  name: 'Pop Culture',
  tagline: 'Movies, music, and memes',
  description: 'Prompts and trivia about Hollywood, hit songs, streaming shows, and the celebrities who keep everyone talking.',
  priceUsdCents: 999,
  emoji: '🎬',
  accentColor: '#db2777',
  quiplashPrompts: [
    { id: 'pc-q001', text: 'The secret real reason Hollywood keeps making sequels', category: 'movies' },
    { id: 'pc-q002', text: 'A Netflix summary for a movie that doesn\'t exist yet but definitely will', category: 'movies' },
    { id: 'pc-q003', text: 'What celebrities say to each other at award shows when cameras aren\'t rolling', category: 'celebrity' },
    { id: 'pc-q004', text: 'A rejected Marvel superhero origin story', category: 'movies' },
    { id: 'pc-q005', text: 'The worst possible Oscar acceptance speech', category: 'movies' },
    { id: 'pc-q006', text: 'What always happens in the 4th act of every reality TV show', category: 'tv' },
    { id: 'pc-q007', text: 'A new reality TV show concept that should never be green-lit', category: 'tv' },
    { id: 'pc-q008', text: 'The most honest Yelp review of a celebrity\'s restaurant', category: 'celebrity' },
    { id: 'pc-q009', text: 'What the background extras in movie scenes are actually thinking', category: 'movies' },
    { id: 'pc-q010', text: 'A deleted scene from any movie that would ruin everything', category: 'movies' },
    { id: 'pc-q011', text: 'The worst possible song to play at a wedding', category: 'music' },
    { id: 'pc-q012', text: 'The least necessary celebrity memoir that somehow got published', category: 'celebrity' },
    { id: 'pc-q013', text: 'What a pop star would actually name their autobiography', category: 'music' },
    { id: 'pc-q014', text: 'The worst possible song lyrics for a car insurance commercial', category: 'music' },
    { id: 'pc-q015', text: 'A crossover episode between two shows that should never, ever meet', category: 'tv' },
    { id: 'pc-q016', text: 'The true origin story of a famous catchphrase', category: 'tv' },
    { id: 'pc-q017', text: 'What actors are Googling about themselves at 3am', category: 'celebrity' },
    { id: 'pc-q018', text: 'The one movie that would immediately end cinema if it got made', category: 'movies' },
    { id: 'pc-q019', text: 'A new music genre that nobody asked for but somehow has a Grammy category', category: 'music' },
    { id: 'pc-q020', text: 'What goes on backstage at a singing competition', category: 'tv' },
    { id: 'pc-q021', text: 'The worst band name that somehow sounds like it could be real', category: 'music' },
    { id: 'pc-q022', text: 'A celebrity\'s completely honest Tinder profile', category: 'celebrity' },
    { id: 'pc-q023', text: 'What the Grammy voters are actually listening to when they vote', category: 'music' },
    { id: 'pc-q024', text: 'The most passive-aggressive celebrity social media post', category: 'celebrity' },
    { id: 'pc-q025', text: 'A streaming algorithm recommendation that went catastrophically wrong', category: 'tv' },
    { id: 'pc-q026', text: 'What the movie director is thinking during an actor\'s "big emotional moment"', category: 'movies' },
    { id: 'pc-q027', text: 'The real secret meaning behind a famous song lyric', category: 'music' },
    { id: 'pc-q028', text: 'A movie trailer voiceover that perfectly describes your actual week', category: 'movies' },
    { id: 'pc-q029', text: 'The one thing that would immediately end a celebrity\'s career', category: 'celebrity' },
    { id: 'pc-q030', text: 'What the composer of a horror movie score is actually listening to for inspiration', category: 'music' },
  ],
  quiplashFinalLash: [
    { id: 'pc-ql01', text: 'The one Hollywood remake that would somehow genuinely improve on the original', category: 'finallash' },
    { id: 'pc-ql02', text: 'The reality TV show that would perfectly capture how the world feels right now', category: 'finallash' },
    { id: 'pc-ql03', text: 'What the internet would do on day one if every streaming service merged into one', category: 'finallash' },
    { id: 'pc-ql04', text: 'The movie that perfectly captures your personality — and why that is deeply concerning', category: 'finallash' },
    { id: 'pc-ql05', text: 'If your life had a theme song, what genre would it be and what would the chorus say', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'The highest-grossing film of all time adjusted for inflation is ___', blank: '___', realAnswer: 'Gone with the Wind', category: 'movies' },
    { text: 'The Beatles were rejected by Decca Records in ___ because "guitar groups are on the way out"', blank: '___', realAnswer: '1962', category: 'music' },
    { text: 'The original title of the sitcom "Friends" was ___', blank: '___', realAnswer: 'Insomnia Café', category: 'tv' },
    { text: 'The actor who played James Bond the most times is ___', blank: '___', realAnswer: 'Roger Moore (7 films)', category: 'movies' },
    { text: '"Jingle Bells" was originally written for ___', blank: '___', realAnswer: 'Thanksgiving, not Christmas', category: 'music' },
    { text: 'The Simpsons predicted Donald Trump\'s presidency in a ___ episode', blank: '___', realAnswer: '2000', category: 'tv' },
    { text: 'The famous Wilhelm Scream sound effect has appeared in over ___ movies', blank: '___', realAnswer: '400', category: 'movies' },
    { text: 'Walt Disney was rejected over ___ times before Disneyland received funding', blank: '___', realAnswer: '302', category: 'celebrity' },
    { text: 'Celine Dion recorded "My Heart Will Go On" in a single unplanned ___', blank: '___', realAnswer: 'take', category: 'music' },
    { text: 'The Super Bowl halftime show was originally performed by ___', blank: '___', realAnswer: 'college marching bands', category: 'music' },
    { text: '"I\'ll be back" in The Terminator was originally scripted as ___', blank: '___', realAnswer: '"I\'ll come back"', category: 'movies' },
    { text: 'The most streamed song on Spotify of all time is ___', blank: '___', realAnswer: '"Blinding Lights" by The Weeknd', category: 'music' },
    { text: 'Keanu Reeves donated most of his salary from The Matrix to ___', blank: '___', realAnswer: 'the special effects and costume crews', category: 'celebrity' },
    { text: 'The shortest Best Picture acceptance speech in Oscar history was ___', blank: '___', realAnswer: '9 seconds', category: 'movies' },
    { text: 'Taylor Swift\'s cats are named after ___', blank: '___', realAnswer: 'fictional TV characters (Olivia Benson, Meredith Grey, Benjamin Button)', category: 'celebrity' },
    { text: 'The first-ever YouTube video uploaded was titled ___', blank: '___', realAnswer: '"Me at the zoo"', category: 'tech' },
    { text: 'The movie "Home Alone" was almost not made because studios thought it was ___', blank: '___', realAnswer: 'too expensive', category: 'movies' },
    { text: 'The Rolling Stones have been on what they call their "farewell tour" since ___', blank: '___', realAnswer: '1989', category: 'music' },
    { text: 'Beyoncé has won ___ Grammy Awards, the most of any artist in history', blank: '___', realAnswer: '32', category: 'music' },
    { text: 'The first video ever to hit 1 billion views on YouTube was ___', blank: '___', realAnswer: '"Gangnam Style" by PSY', category: 'music' },
  ],
  triviaQuestions: [
    {
      id: 'pc-t001',
      text: 'Which movie holds the record for most Academy Award wins?',
      options: ['Three films tie at 11 (Ben-Hur, Titanic, LOTR: Return of the King)', 'Titanic alone', 'Gone with the Wind', 'Schindler\'s List'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'hard',
    },
    {
      id: 'pc-t002',
      text: 'What year did the original Star Wars (Episode IV) release?',
      options: ['1977', '1980', '1975', '1983'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'pc-t003',
      text: 'Who sang "Thriller"?',
      options: ['Michael Jackson', 'Prince', 'David Bowie', 'James Brown'],
      correctIndex: 0,
      category: 'music',
      difficulty: 'easy',
    },
    {
      id: 'pc-t004',
      text: 'What is the name of Tony Stark\'s first AI assistant in the Iron Man films?',
      options: ['JARVIS', 'FRIDAY', 'KAREN', 'HELEN'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'pc-t005',
      text: 'Which TV show received the most Emmy nominations in history?',
      options: ['Game of Thrones', 'Frasier', 'Cheers', 'The West Wing'],
      correctIndex: 0,
      category: 'tv',
      difficulty: 'medium',
    },
    {
      id: 'pc-t006',
      text: 'What group was Beyoncé in before going solo?',
      options: ["Destiny's Child", 'TLC', 'En Vogue', "Girls Aloud"],
      correctIndex: 0,
      category: 'music',
      difficulty: 'easy',
    },
    {
      id: 'pc-t007',
      text: '"I\'m going to make him an offer he can\'t refuse" is a line from which film?',
      options: ['The Godfather', 'Scarface', 'Goodfellas', 'Casino'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'pc-t008',
      text: 'Who was the first person to reach 1 million Twitter followers?',
      options: ['Ashton Kutcher', 'Oprah Winfrey', 'Barack Obama', 'Ellen DeGeneres'],
      correctIndex: 0,
      category: 'celebrity',
      difficulty: 'hard',
    },
    {
      id: 'pc-t009',
      text: 'What is the highest-grossing film franchise of all time?',
      options: ['Marvel Cinematic Universe', 'Star Wars', 'Harry Potter', 'James Bond'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'medium',
    },
    {
      id: 'pc-t010',
      text: 'Who has won the most Grammy Awards of all time?',
      options: ['Beyoncé (32)', 'Taylor Swift', 'Adele', 'Stevie Wonder'],
      correctIndex: 0,
      category: 'music',
      difficulty: 'medium',
    },
    {
      id: 'pc-t011',
      text: 'What is the name of Harry Potter\'s owl?',
      options: ['Hedwig', 'Errol', 'Fawkes', 'Crookshanks'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'pc-t012',
      text: 'How many seasons did "Breaking Bad" run?',
      options: ['5', '4', '6', '7'],
      correctIndex: 0,
      category: 'tv',
      difficulty: 'easy',
    },
    {
      id: 'pc-t013',
      text: '"May the Force be with you" is from which franchise?',
      options: ['Star Wars', 'Star Trek', 'Dune', 'Avatar'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'pc-t014',
      text: 'What color is the Time Infinity Stone in Marvel?',
      options: ['Green', 'Orange', 'Blue', 'Purple'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'medium',
    },
    {
      id: 'pc-t015',
      text: 'How many episodes are in Season 1 of "Stranger Things"?',
      options: ['8', '10', '6', '12'],
      correctIndex: 0,
      category: 'tv',
      difficulty: 'medium',
    },
    {
      id: 'pc-t016',
      text: 'Who played Tony Stark / Iron Man?',
      options: ['Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Jeremy Renner'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'easy',
    },
    {
      id: 'pc-t017',
      text: 'What country does K-pop originate from?',
      options: ['South Korea', 'Japan', 'China', 'Thailand'],
      correctIndex: 0,
      category: 'music',
      difficulty: 'easy',
    },
    {
      id: 'pc-t018',
      text: 'Which streaming service launched first?',
      options: ['Netflix', 'Hulu', 'Amazon Prime Video', 'Disney+'],
      correctIndex: 0,
      category: 'tv',
      difficulty: 'medium',
    },
    {
      id: 'pc-t019',
      text: 'What band wrote and performed "Bohemian Rhapsody"?',
      options: ['Queen', 'Led Zeppelin', 'The Rolling Stones', 'Aerosmith'],
      correctIndex: 0,
      category: 'music',
      difficulty: 'easy',
    },
    {
      id: 'pc-t020',
      text: 'What fictional language is spoken in the "Avatar" (2009) film by the Na\'vi?',
      options: ["Na'vi (created by a linguist)", 'Klingon', 'Elvish', 'Dothraki'],
      correctIndex: 0,
      category: 'movies',
      difficulty: 'medium',
    },
  ],
}

// ── Sports & Games Pack ───────────────────────────────────────────────────────

const sportsGamesPack: ContentPack = {
  id: 'sports-games',
  name: 'Sports & Games',
  tagline: 'Athletes, records, and board game drama',
  description: 'Prompts and trivia about sports legends, athletic feats, board games, and the weird world of competitive everything.',
  priceUsdCents: 999,
  emoji: '⚽',
  accentColor: '#16a34a',
  quiplashPrompts: [
    { id: 'sg-q001', text: 'The worst sports team name imaginable', category: 'sports' },
    { id: 'sg-q002', text: 'What athletes are actually thinking during the national anthem', category: 'sports' },
    { id: 'sg-q003', text: 'A motivational speech that would immediately deflate an entire team', category: 'sports' },
    { id: 'sg-q004', text: 'The least impressive athletic achievement to brag about at a bar', category: 'sports' },
    { id: 'sg-q005', text: 'The worst thing a coach could yell from the sideline', category: 'sports' },
    { id: 'sg-q006', text: 'A new Olympic sport that would end in immediate disaster', category: 'sports' },
    { id: 'sg-q007', text: 'What referees are actually calling people in their heads', category: 'sports' },
    { id: 'sg-q008', text: 'The most passive-aggressive thing a bench player can do', category: 'sports' },
    { id: 'sg-q009', text: 'A sports commentator\'s most embarrassing live hot take', category: 'sports' },
    { id: 'sg-q010', text: 'The worst mascot name for a children\'s recreational league', category: 'sports' },
    { id: 'sg-q011', text: 'What chess grandmasters trash-talk each other about', category: 'games' },
    { id: 'sg-q012', text: 'The world\'s least competitive "sport" that somehow has world championships', category: 'sports' },
    { id: 'sg-q013', text: 'What golfers think about for all 18 holes', category: 'sports' },
    { id: 'sg-q014', text: 'The worst possible way to celebrate a touchdown', category: 'sports' },
    { id: 'sg-q015', text: 'A new rule that would make any sport completely unplayable', category: 'sports' },
    { id: 'sg-q016', text: 'The saddest thing you can overhear at a bowling alley', category: 'sports' },
    { id: 'sg-q017', text: 'What the equipment manager hears in the locker room after a loss', category: 'sports' },
    { id: 'sg-q018', text: 'The rejected slogan for a sports energy drink', category: 'sports' },
    { id: 'sg-q019', text: 'A sports trading card for someone who has never been good at sports', category: 'sports' },
    { id: 'sg-q020', text: 'The real reason nobody watches that one sport you have never seen on TV', category: 'sports' },
    { id: 'sg-q021', text: 'The worst possible nickname for a sports superstar', category: 'sports' },
    { id: 'sg-q022', text: 'What the hot dog vendors at stadiums are really thinking', category: 'sports' },
    { id: 'sg-q023', text: 'The most dramatic way to lose at a board game', category: 'games' },
    { id: 'sg-q024', text: 'A new Monopoly property that would ruin every game night', category: 'games' },
    { id: 'sg-q025', text: 'What happens at an esports tournament after midnight', category: 'games' },
    { id: 'sg-q026', text: 'The most absurd demand in a professional athlete\'s contract rider', category: 'sports' },
    { id: 'sg-q027', text: 'The secret reason tennis players grunt so dramatically', category: 'sports' },
    { id: 'sg-q028', text: 'What the Jeopardy Daily Double sound effect feels like in real life', category: 'games' },
    { id: 'sg-q029', text: 'A cheat code for real life sports that somehow gets approved', category: 'sports' },
    { id: 'sg-q030', text: 'What the guy who lost the chess match to a computer told his family at dinner', category: 'games' },
  ],
  quiplashFinalLash: [
    { id: 'sg-ql01', text: 'The one ridiculous rule you\'d add to any professional sport to make it 1000% more entertaining', category: 'finallash' },
    { id: 'sg-ql02', text: 'The sport that would be invented if you combined the two most boring things about your personality', category: 'finallash' },
    { id: 'sg-ql03', text: 'What you would tell a trophy if it could hear your confession', category: 'finallash' },
    { id: 'sg-ql04', text: 'The real reason the designated hitter rule was actually invented', category: 'finallash' },
    { id: 'sg-ql05', text: 'Your most embarrassing moment in any game — board, card, video, or sport — that you still haven\'t gotten over', category: 'finallash' },
  ],
  fibbagePrompts: [
    { text: 'The fastest hat trick in professional hockey history happened in ___ seconds', blank: '___', realAnswer: '21', category: 'sports' },
    { text: 'A regulation basketball hoop sits exactly ___ feet from the floor', blank: '___', realAnswer: '10', category: 'sports' },
    { text: 'Golf was banned in Scotland for ___ years because soldiers were skipping archery practice', blank: '___', realAnswer: '32', category: 'history' },
    { text: 'The longest match in Wimbledon history lasted ___ hours', blank: '___', realAnswer: '11 hours and 5 minutes', category: 'sports' },
    { text: 'Michael Jordan was cut from his high school basketball team in ___', blank: '___', realAnswer: '10th grade', category: 'sports' },
    { text: 'The original Olympic Games were held to honor the god ___', blank: '___', realAnswer: 'Zeus', category: 'history' },
    { text: 'Barry Bonds hit ___ home runs in the 2001 season, the all-time single-season record', blank: '___', realAnswer: '73', category: 'sports' },
    { text: 'A chess grandmaster named Timur Gareyev once beat 48 opponents simultaneously while ___', blank: '___', realAnswer: 'blindfolded', category: 'games' },
    { text: 'The Super Bowl trophy is named after ___', blank: '___', realAnswer: 'Vince Lombardi', category: 'sports' },
    { text: 'Usain Bolt\'s top speed during his 100m world record run was ___ mph', blank: '___', realAnswer: '27.8', category: 'sports' },
    { text: 'The word "soccer" was invented in ___', blank: '___', realAnswer: 'England', category: 'sports' },
    { text: 'Tiger Woods has won the Masters Tournament ___ times', blank: '___', realAnswer: '5', category: 'sports' },
    { text: 'The world record for the longest Monopoly game played lasted ___ days', blank: '___', realAnswer: '70', category: 'games' },
    { text: 'Basketball was invented by Dr. James Naismith, who was originally from ___', blank: '___', realAnswer: 'Canada', category: 'sports' },
    { text: 'In bowling, three consecutive strikes is called a ___', blank: '___', realAnswer: 'turkey', category: 'sports' },
    { text: 'The fastest goal scored in a professional soccer match happened just ___ seconds in', blank: '___', realAnswer: '2.4', category: 'sports' },
    { text: 'A standard soccer field has no fixed size — it can vary by up to ___ yards in length', blank: '___', realAnswer: '30', category: 'sports' },
    { text: 'The largest crowd to watch a single sporting event was at the 1950 FIFA World Cup final, numbering nearly ___', blank: '___', realAnswer: '200,000 people', category: 'sports' },
    { text: 'The first first-person video game tournament was held in ___ at Stanford University', blank: '___', realAnswer: '1972', category: 'games' },
    { text: 'A major league pitcher\'s fastball must be caught by a catcher\'s mitt in roughly ___ seconds after release', blank: '___', realAnswer: '0.4', category: 'sports' },
  ],
  triviaQuestions: [
    {
      id: 'sg-t001',
      text: 'How many players are on a standard soccer team on the field at one time?',
      options: ['11', '10', '9', '12'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t002',
      text: 'In what city were the first modern Olympic Games held in 1896?',
      options: ['Athens', 'Paris', 'London', 'Rome'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'medium',
    },
    {
      id: 'sg-t003',
      text: 'What does "MVP" stand for in sports?',
      options: ['Most Valuable Player', 'Most Versatile Player', 'Most Voted Player', 'Most Valued Professional'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t004',
      text: 'How many cards are in a standard Uno deck?',
      options: ['108', '52', '80', '120'],
      correctIndex: 0,
      category: 'games',
      difficulty: 'hard',
    },
    {
      id: 'sg-t005',
      text: 'What sport is played at Wimbledon?',
      options: ['Tennis', 'Cricket', 'Badminton', 'Squash'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t006',
      text: 'How many squares are on a standard chess board?',
      options: ['64', '32', '128', '81'],
      correctIndex: 0,
      category: 'games',
      difficulty: 'easy',
    },
    {
      id: 'sg-t007',
      text: 'What country has won the most FIFA World Cups?',
      options: ['Brazil (5)', 'Germany', 'Italy', 'Argentina'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'medium',
    },
    {
      id: 'sg-t008',
      text: 'What is a "perfect game" in bowling?',
      options: ['12 consecutive strikes (score of 300)', '10 strikes in a row', '9 consecutive spares', 'Finishing without any gutter balls'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'medium',
    },
    {
      id: 'sg-t009',
      text: 'Who holds the record for most Olympic gold medals of all time?',
      options: ['Michael Phelps', 'Usain Bolt', 'Carl Lewis', 'Simone Biles'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t010',
      text: 'How many points is a touchdown worth in American football?',
      options: ['6', '7', '5', '3'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t011',
      text: 'What board game uses the pieces Battleship, Thimble, and Top Hat?',
      options: ['Monopoly', 'Clue', 'Risk', 'Sorry!'],
      correctIndex: 0,
      category: 'games',
      difficulty: 'easy',
    },
    {
      id: 'sg-t012',
      text: 'What sport uses a "puck"?',
      options: ['Ice hockey', 'Lacrosse', 'Polo', 'Curling'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t013',
      text: 'How many players are on a standard basketball team on the court?',
      options: ['5', '6', '4', '7'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t014',
      text: 'In chess, which piece can only move diagonally?',
      options: ['Bishop', 'Knight', 'Rook', 'King'],
      correctIndex: 0,
      category: 'games',
      difficulty: 'easy',
    },
    {
      id: 'sg-t015',
      text: 'What is the maximum score possible in a single game of ten-pin bowling?',
      options: ['300', '100', '250', '500'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t016',
      text: 'How long is a standard marathon race?',
      options: ['26.2 miles (42.195 km)', '20 miles', '30 km', '25 miles'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t017',
      text: 'What does "LBW" stand for in cricket?',
      options: ['Leg Before Wicket', 'Left Bat Width', 'Low Bounce Wicket', 'Lateral Bat Wrist'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'hard',
    },
    {
      id: 'sg-t018',
      text: 'In Scrabble, which letter is worth the most points?',
      options: ['Q or Z (10 points each)', 'X (8 points)', 'J or K (8/5 points)', 'V (4 points)'],
      correctIndex: 0,
      category: 'games',
      difficulty: 'medium',
    },
    {
      id: 'sg-t019',
      text: 'How many holes are in a standard round of golf?',
      options: ['18', '12', '9', '24'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'easy',
    },
    {
      id: 'sg-t020',
      text: 'What is the term for when a baseball pitcher strikes out every batter in the game?',
      options: ['Immaculate game', 'Perfect game', 'No-hitter', 'Shutout'],
      correctIndex: 0,
      category: 'sports',
      difficulty: 'hard',
    },
  ],
}

// ── Pack Registry ─────────────────────────────────────────────────────────────

export const CONTENT_PACKS: Record<PackId, ContentPack> = {
  'after-dark': afterDarkPack,
  'nerd-pack': nerdPack,
  'world-tour': worldTourPack,
  'sketch-bluff': sketchBluffPack,
  'pop-culture': popCulturePack,
  'sports-games': sportsGamesPack,
}

export const PACK_ORDER: PackId[] = ['after-dark', 'nerd-pack', 'world-tour', 'sketch-bluff', 'pop-culture', 'sports-games']

export function buildContentLibrary(activeAddOnIds: string[]): ContentLibrary {
  const base: ContentLibrary = {
    quiplashPrompts: QUIPLASH_PROMPTS.filter(p => p.category !== 'finallash'),
    quiplashFinalLash: [...QUIPLASH_FINAL_LASH],
    fibbagePrompts: [...FIBBAGE_PROMPTS],
    triviaQuestions: [...TRIVIA_QUESTIONS],
    sketchbluffPrompts: [...SKETCHBLUFF_PROMPTS],
  }

  for (const id of activeAddOnIds) {
    const pack = CONTENT_PACKS[id as PackId]
    if (!pack) continue
    base.quiplashPrompts = [...base.quiplashPrompts, ...pack.quiplashPrompts]
    base.quiplashFinalLash = [...base.quiplashFinalLash, ...pack.quiplashFinalLash]
    base.fibbagePrompts = [...base.fibbagePrompts, ...pack.fibbagePrompts]
    base.triviaQuestions = [...base.triviaQuestions, ...pack.triviaQuestions]
    if (pack.sketchbluffPrompts) {
      base.sketchbluffPrompts = [...base.sketchbluffPrompts, ...pack.sketchbluffPrompts]
    }
  }

  return base
}
