import type { FibbagePrompt } from '../types/fibbage'
import type { TriviaQuestion } from '../types/trivia'

export interface QuiplashPromptDef {
  id: string
  text: string
  category: string
}

// ── Quiplash Prompts ──────────────────────────────────────────────────────────

export const QUIPLASH_PROMPTS: QuiplashPromptDef[] = [
  // Jobs & Work
  { id: 'q001', text: 'A terrible superpower for a dentist', category: 'jobs' },
  { id: 'q002', text: 'The worst job interview answer you could give', category: 'jobs' },
  { id: 'q003', text: 'What a CEO actually does all day', category: 'jobs' },
  { id: 'q004', text: 'A new job title that sounds impressive but means nothing', category: 'jobs' },
  { id: 'q005', text: 'The worst thing to put on a business card', category: 'jobs' },
  { id: 'q006', text: 'An awful motivational poster for the office', category: 'jobs' },
  { id: 'q007', text: 'A job that should exist but doesn\'t', category: 'jobs' },

  // Food
  { id: 'q010', text: 'The worst thing to discover at a pizza buffet', category: 'food' },
  { id: 'q011', text: 'A food combination that would end a friendship', category: 'food' },
  { id: 'q012', text: 'What fast food workers whisper to the burgers', category: 'food' },
  { id: 'q013', text: 'A new flavor of ice cream that nobody asked for', category: 'food' },
  { id: 'q014', text: 'The worst name for a restaurant', category: 'food' },
  { id: 'q015', text: 'A "health food" that is definitely not healthy', category: 'food' },
  { id: 'q016', text: 'What chefs say when nobody\'s watching', category: 'food' },
  { id: 'q017', text: 'The most disappointing thing to find in a birthday cake', category: 'food' },

  // Animals
  { id: 'q020', text: 'What dogs actually think about when they stare at you', category: 'animals' },
  { id: 'q021', text: 'The first rule of being a cat', category: 'animals' },
  { id: 'q022', text: 'A rejected animal superpower', category: 'animals' },
  { id: 'q023', text: 'What squirrels are REALLY burying out there', category: 'animals' },
  { id: 'q024', text: 'What bears say to each other in the woods', category: 'animals' },
  { id: 'q025', text: 'If sharks had one request for humans', category: 'animals' },
  { id: 'q026', text: 'The worst pet a villain could have', category: 'animals' },
  { id: 'q027', text: 'What the seagulls are plotting', category: 'animals' },

  // Society & Daily Life
  { id: 'q030', text: 'The most passive-aggressive sticky note ever left in a shared fridge', category: 'society' },
  { id: 'q031', text: 'The world would be better if everyone just agreed to stop ___', category: 'society' },
  { id: 'q032', text: 'A new law nobody asked for but that would help everyone', category: 'society' },
  { id: 'q033', text: 'The real reason the internet was invented', category: 'society' },
  { id: 'q034', text: 'A terrible idea for a social media platform', category: 'society' },
  { id: 'q035', text: 'The worst thing to text your boss by accident', category: 'society' },
  { id: 'q036', text: 'Something everyone pretends to like but secretly hates', category: 'society' },
  { id: 'q037', text: 'The most polite way to tell someone their breath is terrible', category: 'society' },
  { id: 'q038', text: 'A sign that would cause the most chaos in an elevator', category: 'society' },
  { id: 'q039', text: 'What people are REALLY thinking at family dinners', category: 'society' },

  // Superhero / Fantasy
  { id: 'q040', text: 'The worst weakness for a superhero to have', category: 'superhero' },
  { id: 'q041', text: 'A superhero whose power sounds great but is actually useless', category: 'superhero' },
  { id: 'q042', text: 'What supervillains do on their day off', category: 'superhero' },
  { id: 'q043', text: 'The world\'s lamest secret identity', category: 'superhero' },
  { id: 'q044', text: 'The worst thing to say when you\'re supposed to be saving the world', category: 'superhero' },
  { id: 'q045', text: 'A spell that a terrible wizard would cast', category: 'superhero' },

  // Science & Technology
  { id: 'q050', text: 'The app that should NOT be invented', category: 'tech' },
  { id: 'q051', text: 'What AI actually says about humans when we\'re not listening', category: 'tech' },
  { id: 'q052', text: 'A futuristic invention nobody will actually use', category: 'tech' },
  { id: 'q053', text: 'The password hint that gives away everything', category: 'tech' },
  { id: 'q054', text: 'A terrible robot feature', category: 'tech' },
  { id: 'q055', text: 'What happens when the WiFi goes out and people forget how to function', category: 'tech' },

  // History & School
  { id: 'q060', text: 'Something historians definitely got wrong about ancient Rome', category: 'history' },
  { id: 'q061', text: 'What George Washington was REALLY thinking at Valley Forge', category: 'history' },
  { id: 'q062', text: 'The worst excuse a student has ever given for not doing homework', category: 'school' },
  { id: 'q063', text: 'A subject that should be taught in school but isn\'t', category: 'school' },
  { id: 'q064', text: 'The most useless thing you learned in school', category: 'school' },

  // Random Absurdity
  { id: 'q070', text: 'The worst thing to say at a wedding toast', category: 'absurd' },
  { id: 'q071', text: 'The most suspicious item on a receipt', category: 'absurd' },
  { id: 'q072', text: 'A terrible thing to whisper to a stranger on the subway', category: 'absurd' },
  { id: 'q073', text: 'The laziest way to solve a world problem', category: 'absurd' },
  { id: 'q074', text: 'What\'s actually happening inside vending machines at night', category: 'absurd' },
  { id: 'q075', text: 'A conspiracy theory that would make everything make MORE sense', category: 'absurd' },
  { id: 'q076', text: 'The worst thing to find in your seat on a plane', category: 'absurd' },
  { id: 'q077', text: 'What clowns tell each other at clown school', category: 'absurd' },
  { id: 'q078', text: 'The rejected tagline for a famous brand', category: 'absurd' },
  { id: 'q079', text: 'A theme park ride that should be shut down immediately', category: 'absurd' },
  { id: 'q080', text: 'What the moon is actually made of (scientists are lying)', category: 'absurd' },
  { id: 'q081', text: 'The one thing that would make chess more exciting', category: 'absurd' },
  { id: 'q082', text: 'Why aliens have never visited Earth', category: 'absurd' },
  { id: 'q083', text: 'The worst thing to name a baby', category: 'absurd' },
  { id: 'q084', text: 'The most unconvincing disguise', category: 'absurd' },
  { id: 'q085', text: 'A terrible product description for a toilet plunger', category: 'absurd' },
  { id: 'q086', text: 'What ghosts are actually doing in your house', category: 'absurd' },
  { id: 'q087', text: 'The one skill that would make someone unstoppable', category: 'absurd' },
  { id: 'q088', text: 'What\'s printed on the world\'s most useless trophy', category: 'absurd' },
  { id: 'q089', text: 'The worst inspirational quote of all time', category: 'absurd' },
  { id: 'q090', text: 'A terrible name for a new country', category: 'absurd' },
  { id: 'q091', text: 'What would happen if dogs could talk for one day', category: 'absurd' },
  { id: 'q092', text: 'The real reason socks always go missing in the dryer', category: 'absurd' },
  { id: 'q093', text: 'A rejected McDonald\'s mascot', category: 'absurd' },
  { id: 'q094', text: 'The worst possible thing to say in a job reference', category: 'absurd' },
  { id: 'q095', text: 'What pirates actually argued about', category: 'absurd' },
  { id: 'q096', text: 'The most cursed museum exhibit', category: 'absurd' },
  { id: 'q097', text: 'The thing you\'d find in Santa\'s search history', category: 'absurd' },
  { id: 'q098', text: 'The world\'s worst self-help book title', category: 'absurd' },
  { id: 'q099', text: 'A terrible slogan for a funeral home', category: 'absurd' },
  { id: 'q100', text: 'What the statue in the town square is ACTUALLY thinking', category: 'absurd' },
  { id: 'q101', text: 'A weird thing to announce before cutting a cake', category: 'absurd' },
  { id: 'q102', text: 'The worst prize in a game show grab bag', category: 'absurd' },
  { id: 'q103', text: 'What the dentist hears when your mouth is full of tools', category: 'absurd' },
  { id: 'q104', text: 'A terrible slogan for a retirement village', category: 'absurd' },
  { id: 'q105', text: 'The least helpful thing to say during a fire drill', category: 'absurd' },
  { id: 'q106', text: 'What a haunted printer would print first', category: 'tech' },
  { id: 'q107', text: 'A phone notification nobody wants to receive', category: 'tech' },
  { id: 'q108', text: 'The worst feature for a smart refrigerator', category: 'tech' },
  { id: 'q109', text: 'A suspicious name for a new dating app', category: 'tech' },
  { id: 'q110', text: 'The first thing a self-aware toaster would demand', category: 'tech' },
  { id: 'q111', text: 'A new office rule that would start a rebellion', category: 'jobs' },
  { id: 'q112', text: 'The worst thing to say in an all-hands meeting', category: 'jobs' },
  { id: 'q113', text: 'A corporate perk that is secretly a punishment', category: 'jobs' },
  { id: 'q114', text: 'The most dramatic way to quit a boring job', category: 'jobs' },
  { id: 'q115', text: 'A resume skill that raises more questions than it answers', category: 'jobs' },
  { id: 'q116', text: 'A restaurant special that sounds illegal', category: 'food' },
  { id: 'q117', text: 'The worst thing for a waiter to call you', category: 'food' },
  { id: 'q118', text: 'A cereal mascot that children would fear', category: 'food' },
  { id: 'q119', text: 'The saddest possible fortune cookie message', category: 'food' },
  { id: 'q120', text: 'A pizza topping that proves society has gone too far', category: 'food' },
  { id: 'q121', text: 'What houseplants complain about when you leave the room', category: 'animals' },
  { id: 'q122', text: 'The worst animal to hire as a babysitter', category: 'animals' },
  { id: 'q123', text: 'What ducks are yelling about all day', category: 'animals' },
  { id: 'q124', text: 'A pet trick that would get you banned from the park', category: 'animals' },
  { id: 'q125', text: 'The secret hobby of every hamster', category: 'animals' },
  { id: 'q126', text: 'A terrible name for a neighborhood watch group', category: 'society' },
  { id: 'q127', text: 'The worst thing to say while holding an elevator door', category: 'society' },
  { id: 'q128', text: 'A tiny inconvenience that should be a federal crime', category: 'society' },
  { id: 'q129', text: 'The most alarming thing to hear from your rideshare driver', category: 'society' },
  { id: 'q130', text: 'A new holiday that would immediately get out of hand', category: 'society' },
  { id: 'q131', text: 'The worst magical item to find in a thrift store', category: 'superhero' },
  { id: 'q132', text: 'A superhero catchphrase that needs work', category: 'superhero' },
  { id: 'q133', text: 'A villain plan that is technically just rude', category: 'superhero' },
  { id: 'q134', text: 'The least impressive thing to summon with magic', category: 'superhero' },
  { id: 'q135', text: 'A fantasy kingdom with a deeply boring curse', category: 'superhero' },
  { id: 'q136', text: 'The worst school assembly topic', category: 'school' },
  { id: 'q137', text: 'A field trip destination that should require a waiver', category: 'school' },
  { id: 'q138', text: 'The worst thing to write in a yearbook', category: 'school' },
  { id: 'q139', text: 'A historical event that was probably caused by one awkward text', category: 'history' },
  { id: 'q140', text: 'What medieval knights complained about after work', category: 'history' },
  { id: 'q141', text: 'The wrong way to impress someone at karaoke', category: 'absurd' },
  { id: 'q142', text: 'A dangerous thing to make into a scented candle', category: 'absurd' },
  { id: 'q143', text: 'The worst thing to hear from a mall Santa', category: 'absurd' },
  { id: 'q144', text: 'A museum audio guide that has given up', category: 'absurd' },
  { id: 'q145', text: 'The least romantic thing to skywrite', category: 'absurd' },

  // Final Lash prompts (used for round 3, all players answer same one)
  { id: 'ql01', text: 'The worst thing to say to your doctor', category: 'finallash' },
  { id: 'ql02', text: 'The ultimate excuse for being late', category: 'finallash' },
  { id: 'ql03', text: 'What would be written on a warning label for being a person', category: 'finallash' },
  { id: 'ql04', text: 'The most embarrassing thing that could happen at the gym', category: 'finallash' },
  { id: 'ql05', text: 'The real reason you never see Batman and Superman in the same room', category: 'finallash' },
  { id: 'ql06', text: 'The world\'s most unnecessary invention', category: 'finallash' },
  { id: 'ql07', text: 'Something a time traveler would hate about the future', category: 'finallash' },
  { id: 'ql08', text: 'The worst secret to reveal during a talent show', category: 'finallash' },
  { id: 'ql09', text: 'The title of the world\'s least inspiring autobiography', category: 'finallash' },
  { id: 'ql10', text: 'What humanity should apologize to aliens for first', category: 'finallash' },
  { id: 'ql11', text: 'The first sentence of a truly terrible fairy tale', category: 'finallash' },
  { id: 'ql12', text: 'A warning label that should be printed on your hometown', category: 'finallash' },
]

// ── Fibbage Prompts ───────────────────────────────────────────────────────────

export const FIBBAGE_PROMPTS: Omit<FibbagePrompt, 'id' | 'playerEntries' | 'submitted' | 'choices'>[] = [
  { text: 'The original name for Google was ___', blank: '___', realAnswer: 'BackRub', category: 'tech' },
  { text: 'A day\'s worth of global internet traffic would fill ___ Libraries of Congress', blank: '___', realAnswer: '4 million', category: 'tech' },
  { text: 'In Japan, there is a museum dedicated entirely to ___', blank: '___', realAnswer: 'instant ramen', category: 'food' },
  { text: 'The world record for most T-shirts worn at once is ___', blank: '___', realAnswer: '260', category: 'records' },
  { text: 'Honey never spoils — archaeologists found 3000-year-old honey in ___ that was still edible', blank: '___', realAnswer: 'Egyptian tombs', category: 'history' },
  { text: 'Cleopatra lived closer in time to the moon landing than to ___ being built', blank: '___', realAnswer: 'the Great Pyramid', category: 'history' },
  { text: 'Oxford University is older than ___ by at least 300 years', blank: '___', realAnswer: 'the Aztec Empire', category: 'history' },
  { text: 'The country with the most naturally occurring lakes is ___', blank: '___', realAnswer: 'Canada', category: 'geography' },
  { text: 'A group of flamingos is called a ___', blank: '___', realAnswer: 'flamboyance', category: 'animals' },
  { text: 'Octopuses have ___ hearts', blank: '___', realAnswer: 'three', category: 'animals' },
  { text: 'The inventor of the frisbee was turned into a frisbee after death — his ashes were made into a frisbee by ___', blank: '___', realAnswer: 'his family\'s request', category: 'weird' },
  { text: 'The shortest war in history lasted ___ minutes', blank: '___', realAnswer: '38', category: 'history' },
  { text: 'The average cloud weighs about ___ pounds', blank: '___', realAnswer: '1.1 million', category: 'science' },
  { text: 'Butterflies taste with their ___', blank: '___', realAnswer: 'feet', category: 'animals' },
  { text: 'The country that consumes the most chocolate per capita is ___', blank: '___', realAnswer: 'Switzerland', category: 'food' },
  { text: 'IKEA is named after its founder, Ingvar Kamprad, and his farm in ___', blank: '___', realAnswer: 'Elmtaryd, Agunnaryd', category: 'business' },
  { text: 'It rains ___ on Venus', blank: '___', realAnswer: 'sulfuric acid', category: 'science' },
  { text: 'The hashtag symbol is technically called an ___', blank: '___', realAnswer: 'octothorpe', category: 'language' },
  { text: 'The most stolen book from public libraries is ___', blank: '___', realAnswer: 'the Guinness Book of World Records', category: 'books' },
  { text: 'A snail can sleep for ___ years', blank: '___', realAnswer: 'three', category: 'animals' },
  { text: 'The Great Wall of China was partly built with ___', blank: '___', realAnswer: 'sticky rice', category: 'history' },
  { text: 'The first YouTube video ever uploaded was about ___', blank: '___', realAnswer: 'elephants at a zoo', category: 'tech' },
  { text: 'The original color of Coca-Cola was ___', blank: '___', realAnswer: 'green', category: 'food' },
  { text: 'The fear of long words is called ___', blank: '___', realAnswer: 'hippopotomonstrosesquippedaliophobia', category: 'language' },
  { text: 'Scotland\'s national animal is the ___', blank: '___', realAnswer: 'unicorn', category: 'animals' },
  { text: 'The dot above the letter i is called a ___', blank: '___', realAnswer: 'tittle', category: 'language' },
  { text: 'The first item ever sold on eBay was a ___', blank: '___', realAnswer: 'broken laser pointer', category: 'business' },
  { text: 'The sun is about ___ times the size of Earth', blank: '___', realAnswer: '1.3 million', category: 'science' },
  { text: 'The world\'s largest snowflake was recorded in Montana in 1887 and measured ___ inches wide', blank: '___', realAnswer: '15', category: 'nature' },
  { text: 'The country that has won the most Nobel Prizes per capita is ___', blank: '___', realAnswer: 'Switzerland', category: 'education' },
  { text: 'Bananas are technically classified as a ___', blank: '___', realAnswer: 'herb', category: 'food' },
  { text: 'In 1998, Sony accidentally shipped ___ inside some of its floppy disks', blank: '___', realAnswer: 'a virus', category: 'tech' },
  { text: 'The world\'s oldest known living organism is ___ in California', blank: '___', realAnswer: 'a bristlecone pine', category: 'nature' },
  { text: 'The first animated feature film ever made was produced in ___', blank: '___', realAnswer: 'Argentina', category: 'entertainment' },
  { text: 'The average person walks the equivalent of ___ times around the world in a lifetime', blank: '___', realAnswer: 'five', category: 'science' },
  { text: 'Crows can remember human ___ for years', blank: '___', realAnswer: 'faces', category: 'animals' },
  { text: 'The world\'s most expensive spice by weight is ___', blank: '___', realAnswer: 'saffron', category: 'food' },
  { text: 'A shrimp\'s heart is located in its ___', blank: '___', realAnswer: 'head', category: 'animals' },
  { text: 'The only letter that doesn\'t appear in any US state name is ___', blank: '___', realAnswer: 'Q', category: 'geography' },
  { text: 'There are more possible iterations of a game of chess than there are ___ in the observable universe', blank: '___', realAnswer: 'atoms', category: 'science' },
  { text: 'The first oranges were not orange, but ___', blank: '___', realAnswer: 'green', category: 'food' },
  { text: 'The longest hiccuping spell on record lasted about ___ years', blank: '___', realAnswer: '68', category: 'records' },
  { text: 'The national sport of Bhutan is ___', blank: '___', realAnswer: 'archery', category: 'sports' },
  { text: 'The first product to have a barcode scanned in a store was a pack of ___', blank: '___', realAnswer: 'Wrigley\'s gum', category: 'business' },
  { text: 'The longest English word typed with only the left hand is ___', blank: '___', realAnswer: 'stewardesses', category: 'language' },
  { text: 'The Eiffel Tower can be about ___ inches taller during hot weather', blank: '___', realAnswer: '6', category: 'science' },
  { text: 'The tiny pocket inside jeans was originally made for ___', blank: '___', realAnswer: 'pocket watches', category: 'fashion' },
  { text: 'A group of owls is called a ___', blank: '___', realAnswer: 'parliament', category: 'animals' },
  { text: 'The first computer mouse was made mostly of ___', blank: '___', realAnswer: 'wood', category: 'tech' },
  { text: 'The dot over a lowercase j is also called a ___', blank: '___', realAnswer: 'tittle', category: 'language' },
  { text: 'The unicorn is the national animal of ___', blank: '___', realAnswer: 'Scotland', category: 'animals' },
  { text: 'The Canary Islands are named after ___', blank: '___', realAnswer: 'dogs', category: 'geography' },
  { text: 'The first VCR was about the size of a ___', blank: '___', realAnswer: 'piano', category: 'tech' },
  { text: 'The longest place name in Europe belongs to a village in ___', blank: '___', realAnswer: 'Wales', category: 'geography' },
  { text: 'The first alarm clock could only ring at ___ a.m.', blank: '___', realAnswer: '4', category: 'history' },
  { text: 'The world\'s quietest room is located in ___', blank: '___', realAnswer: 'Minnesota', category: 'science' },
  { text: 'The first item purchased by scanning a barcode is now displayed in the ___', blank: '___', realAnswer: 'Smithsonian', category: 'business' },
  { text: 'The longest wedding veil on record was longer than ___ football fields', blank: '___', realAnswer: '63', category: 'records' },
  { text: 'The word robot comes from a Czech word meaning ___', blank: '___', realAnswer: 'forced labor', category: 'language' },
  { text: 'The only mammal capable of true sustained flight is the ___', blank: '___', realAnswer: 'bat', category: 'animals' },
  { text: 'The first person convicted of speeding was going ___ miles per hour', blank: '___', realAnswer: '8', category: 'history' },
  { text: 'Bubble wrap was originally invented as ___', blank: '___', realAnswer: 'wallpaper', category: 'business' },
  { text: 'The largest desert in the world is ___', blank: '___', realAnswer: 'Antarctica', category: 'geography' },
  { text: 'The longest recorded flight of a chicken lasted ___ seconds', blank: '___', realAnswer: '13', category: 'animals' },
  { text: 'The first domain name ever registered was ___', blank: '___', realAnswer: 'symbolics.com', category: 'tech' },
  { text: 'The ampersand used to be considered the ___ letter of the alphabet', blank: '___', realAnswer: '27th', category: 'language' },
  { text: 'A jiffy is an actual unit of time equal to about ___ of a second in electronics', blank: '___', realAnswer: '1/60th', category: 'science' },
  { text: 'The first toy advertised on television was ___', blank: '___', realAnswer: 'Mr. Potato Head', category: 'entertainment' },
  { text: 'The inventor of the Pringles can had some of his ashes buried in a ___', blank: '___', realAnswer: 'Pringles can', category: 'weird' },
  { text: 'The longest Monopoly game reportedly lasted ___ days', blank: '___', realAnswer: '70', category: 'games' },
  { text: 'The state with the highest percentage of forest cover is ___', blank: '___', realAnswer: 'Maine', category: 'geography' },
  { text: 'The world\'s oldest known recipe is for ___', blank: '___', realAnswer: 'beer', category: 'food' },
  { text: 'The plastic tips on shoelaces are called ___', blank: '___', realAnswer: 'aglets', category: 'language' },
  { text: 'The first email was sent by a programmer named ___', blank: '___', realAnswer: 'Ray Tomlinson', category: 'tech' },
  { text: 'A group of porcupines is called a ___', blank: '___', realAnswer: 'prickle', category: 'animals' },
  { text: 'The largest volcano in the solar system is on ___', blank: '___', realAnswer: 'Mars', category: 'science' },
  { text: 'The longest-running scripted TV show in the US is ___', blank: '___', realAnswer: 'The Simpsons', category: 'entertainment' },
  { text: 'The first country to grant women the right to vote was ___', blank: '___', realAnswer: 'New Zealand', category: 'history' },
  { text: 'The most common street name in the United States is ___', blank: '___', realAnswer: 'Second Street', category: 'geography' },
  { text: 'The smell after rain is called ___', blank: '___', realAnswer: 'petrichor', category: 'language' },
  { text: 'The longest human necks are traditionally associated with the Kayan people of ___', blank: '___', realAnswer: 'Myanmar', category: 'culture' },
  { text: 'The largest internal organ in the human body is the ___', blank: '___', realAnswer: 'liver', category: 'science' },
  { text: 'The first feature-length animated movie was made in ___', blank: '___', realAnswer: 'Argentina', category: 'entertainment' },
  { text: 'A group of ferrets is called a ___', blank: '___', realAnswer: 'business', category: 'animals' },
  { text: 'The strongest muscle by weight in the human body is often said to be the ___', blank: '___', realAnswer: 'masseter', category: 'science' },
  { text: 'The first known vending machine dispensed ___', blank: '___', realAnswer: 'holy water', category: 'history' },
  { text: 'The name Lego comes from Danish words meaning ___', blank: '___', realAnswer: 'play well', category: 'business' },
  { text: 'The longest river entirely within one country is the ___', blank: '___', realAnswer: 'Yangtze', category: 'geography' },
  { text: 'The world\'s first novel is often considered to be ___', blank: '___', realAnswer: 'The Tale of Genji', category: 'books' },
  { text: 'The first successful vaccine was developed against ___', blank: '___', realAnswer: 'smallpox', category: 'science' },
]

// ── Trivia Questions ──────────────────────────────────────────────────────────

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: 't001', category: 'Geography', difficulty: 'easy',
    text: 'What is the capital of Australia?',
    options: ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    correctIndex: 0,
  },
  {
    id: 't002', category: 'Science', difficulty: 'easy',
    text: 'What is the chemical symbol for gold?',
    options: ['Au', 'Ag', 'Fe', 'Go'],
    correctIndex: 0,
  },
  {
    id: 't003', category: 'Pop Culture', difficulty: 'easy',
    text: 'How many seasons of "The Office" (US) are there?',
    options: ['9', '7', '8', '10'],
    correctIndex: 0,
  },
  {
    id: 't004', category: 'History', difficulty: 'medium',
    text: 'In what year did World War I begin?',
    options: ['1914', '1916', '1918', '1912'],
    correctIndex: 0,
  },
  {
    id: 't005', category: 'Science', difficulty: 'medium',
    text: 'Which planet has the most moons?',
    options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
    correctIndex: 0,
  },
  {
    id: 't006', category: 'Geography', difficulty: 'medium',
    text: 'Which country has the longest coastline?',
    options: ['Canada', 'Russia', 'Australia', 'Norway'],
    correctIndex: 0,
  },
  {
    id: 't007', category: 'Pop Culture', difficulty: 'easy',
    text: 'What color is Thanos\'s skin?',
    options: ['Purple', 'Blue', 'Green', 'Gray'],
    correctIndex: 0,
  },
  {
    id: 't008', category: 'Food', difficulty: 'easy',
    text: 'What is the main ingredient in guacamole?',
    options: ['Avocado', 'Tomato', 'Lime', 'Jalapeño'],
    correctIndex: 0,
  },
  {
    id: 't009', category: 'Science', difficulty: 'hard',
    text: 'What is the powerhouse of the cell?',
    options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus'],
    correctIndex: 0,
  },
  {
    id: 't010', category: 'History', difficulty: 'hard',
    text: 'The Berlin Wall fell in what year?',
    options: ['1989', '1991', '1987', '1993'],
    correctIndex: 0,
  },
  {
    id: 't011', category: 'Sports', difficulty: 'easy',
    text: 'How many players are on a basketball team on the court at once?',
    options: ['5', '6', '4', '7'],
    correctIndex: 0,
  },
  {
    id: 't012', category: 'Music', difficulty: 'medium',
    text: 'Which band released the album "Dark Side of the Moon"?',
    options: ['Pink Floyd', 'Led Zeppelin', 'The Beatles', 'The Who'],
    correctIndex: 0,
  },
  {
    id: 't013', category: 'Science', difficulty: 'medium',
    text: 'How many bones are in the adult human body?',
    options: ['206', '212', '196', '225'],
    correctIndex: 0,
  },
  {
    id: 't014', category: 'Pop Culture', difficulty: 'medium',
    text: 'In "Harry Potter," what is the name of Harry\'s owl?',
    options: ['Hedwig', 'Errol', 'Pigwidgeon', 'Fawkes'],
    correctIndex: 0,
  },
  {
    id: 't015', category: 'Geography', difficulty: 'hard',
    text: 'What is the smallest country in the world by area?',
    options: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
    correctIndex: 0,
  },
  {
    id: 't016', category: 'Language', difficulty: 'medium',
    text: 'What is the most spoken language in the world by native speakers?',
    options: ['Mandarin Chinese', 'English', 'Spanish', 'Hindi'],
    correctIndex: 0,
  },
  {
    id: 't017', category: 'Science', difficulty: 'easy',
    text: 'What gas do plants absorb from the atmosphere during photosynthesis?',
    options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
    correctIndex: 0,
  },
  {
    id: 't018', category: 'History', difficulty: 'medium',
    text: 'Who painted the Mona Lisa?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Botticelli'],
    correctIndex: 0,
  },
  {
    id: 't019', category: 'Weird Facts', difficulty: 'hard',
    text: 'Which of these animals can survive being frozen solid?',
    options: ['Wood frog', 'Polar bear', 'Arctic fox', 'Siberian tiger'],
    correctIndex: 0,
  },
  {
    id: 't020', category: 'Pop Culture', difficulty: 'easy',
    text: 'What does the "E" in Chuck E. Cheese stand for?',
    options: ['Entertainment', 'Edward', 'Excellent', 'Eddy'],
    correctIndex: 0,
  },
  {
    id: 't021', category: 'Geography', difficulty: 'easy',
    text: 'Which ocean is the largest?',
    options: ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
    correctIndex: 0,
  },
  {
    id: 't022', category: 'Science', difficulty: 'easy',
    text: 'What planet is known as the Red Planet?',
    options: ['Mars', 'Venus', 'Mercury', 'Jupiter'],
    correctIndex: 0,
  },
  {
    id: 't023', category: 'History', difficulty: 'easy',
    text: 'Who was the first president of the United States?',
    options: ['George Washington', 'Thomas Jefferson', 'John Adams', 'Abraham Lincoln'],
    correctIndex: 0,
  },
  {
    id: 't024', category: 'Food', difficulty: 'easy',
    text: 'Sushi is most strongly associated with which country?',
    options: ['Japan', 'China', 'Thailand', 'Vietnam'],
    correctIndex: 0,
  },
  {
    id: 't025', category: 'Music', difficulty: 'easy',
    text: 'How many strings does a standard guitar usually have?',
    options: ['6', '4', '5', '7'],
    correctIndex: 0,
  },
  {
    id: 't026', category: 'Science', difficulty: 'medium',
    text: 'What is the hardest natural substance on Earth?',
    options: ['Diamond', 'Quartz', 'Granite', 'Steel'],
    correctIndex: 0,
  },
  {
    id: 't027', category: 'Geography', difficulty: 'medium',
    text: 'Which country is home to the city of Marrakech?',
    options: ['Morocco', 'Egypt', 'Turkey', 'Spain'],
    correctIndex: 0,
  },
  {
    id: 't028', category: 'Sports', difficulty: 'easy',
    text: 'In soccer, what part of the body can a goalkeeper legally use that most players cannot?',
    options: ['Hands', 'Knees', 'Shoulders', 'Head'],
    correctIndex: 0,
  },
  {
    id: 't029', category: 'Language', difficulty: 'medium',
    text: 'What language has the most native speakers worldwide?',
    options: ['Mandarin Chinese', 'Spanish', 'English', 'Arabic'],
    correctIndex: 0,
  },
  {
    id: 't030', category: 'Science', difficulty: 'medium',
    text: 'What part of the atom has a negative charge?',
    options: ['Electron', 'Proton', 'Neutron', 'Nucleus'],
    correctIndex: 0,
  },
  {
    id: 't031', category: 'History', difficulty: 'medium',
    text: 'The Renaissance began in which modern-day country?',
    options: ['Italy', 'France', 'Germany', 'Greece'],
    correctIndex: 0,
  },
  {
    id: 't032', category: 'Pop Culture', difficulty: 'easy',
    text: 'Which movie features the song "Let It Go"?',
    options: ['Frozen', 'Moana', 'Tangled', 'Brave'],
    correctIndex: 0,
  },
  {
    id: 't033', category: 'Science', difficulty: 'hard',
    text: 'What is the most abundant gas in Earth\'s atmosphere?',
    options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'],
    correctIndex: 0,
  },
  {
    id: 't034', category: 'Geography', difficulty: 'hard',
    text: 'What is the capital of Mongolia?',
    options: ['Ulaanbaatar', 'Astana', 'Bishkek', 'Tashkent'],
    correctIndex: 0,
  },
  {
    id: 't035', category: 'Books', difficulty: 'medium',
    text: 'Who wrote "Pride and Prejudice"?',
    options: ['Jane Austen', 'Charlotte Bronte', 'Mary Shelley', 'Emily Dickinson'],
    correctIndex: 0,
  },
  {
    id: 't036', category: 'Food', difficulty: 'medium',
    text: 'What is the main ingredient in traditional hummus?',
    options: ['Chickpeas', 'Lentils', 'Sesame seeds', 'Eggplant'],
    correctIndex: 0,
  },
  {
    id: 't037', category: 'Sports', difficulty: 'medium',
    text: 'In tennis, what score comes after deuce if one player wins the next point?',
    options: ['Advantage', 'Love', 'Set point', 'Break'],
    correctIndex: 0,
  },
  {
    id: 't038', category: 'Science', difficulty: 'easy',
    text: 'What force keeps planets in orbit around the Sun?',
    options: ['Gravity', 'Magnetism', 'Friction', 'Electricity'],
    correctIndex: 0,
  },
  {
    id: 't039', category: 'History', difficulty: 'hard',
    text: 'Which empire was ruled by Suleiman the Magnificent?',
    options: ['Ottoman Empire', 'Roman Empire', 'Mughal Empire', 'Byzantine Empire'],
    correctIndex: 0,
  },
  {
    id: 't040', category: 'Geography', difficulty: 'medium',
    text: 'Which river runs through Paris?',
    options: ['Seine', 'Thames', 'Danube', 'Rhine'],
    correctIndex: 0,
  },
  {
    id: 't041', category: 'Science', difficulty: 'medium',
    text: 'What is the pH value of pure water at room temperature?',
    options: ['7', '0', '5', '14'],
    correctIndex: 0,
  },
  {
    id: 't042', category: 'Music', difficulty: 'medium',
    text: 'Which instrument has keys, pedals, and strings?',
    options: ['Piano', 'Saxophone', 'Accordion', 'Harp'],
    correctIndex: 0,
  },
  {
    id: 't043', category: 'Pop Culture', difficulty: 'medium',
    text: 'What is the name of the fictional country in "Black Panther"?',
    options: ['Wakanda', 'Genovia', 'Latveria', 'Zamunda'],
    correctIndex: 0,
  },
  {
    id: 't044', category: 'Language', difficulty: 'hard',
    text: 'What does the Latin phrase "carpe diem" mean?',
    options: ['Seize the day', 'Know thyself', 'After death', 'To the stars'],
    correctIndex: 0,
  },
  {
    id: 't045', category: 'Science', difficulty: 'hard',
    text: 'Which scientist developed the three laws of motion?',
    options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Niels Bohr'],
    correctIndex: 0,
  },
  {
    id: 't046', category: 'History', difficulty: 'easy',
    text: 'The pyramids of Giza are in which country?',
    options: ['Egypt', 'Mexico', 'Peru', 'India'],
    correctIndex: 0,
  },
  {
    id: 't047', category: 'Geography', difficulty: 'easy',
    text: 'What is the tallest mountain above sea level?',
    options: ['Mount Everest', 'K2', 'Kilimanjaro', 'Denali'],
    correctIndex: 0,
  },
  {
    id: 't048', category: 'Food', difficulty: 'hard',
    text: 'Which spice is traditionally used to give paella its yellow color?',
    options: ['Saffron', 'Turmeric', 'Paprika', 'Cumin'],
    correctIndex: 0,
  },
  {
    id: 't049', category: 'Sports', difficulty: 'medium',
    text: 'How many bases are on a baseball diamond?',
    options: ['4', '3', '5', '6'],
    correctIndex: 0,
  },
  {
    id: 't050', category: 'Books', difficulty: 'easy',
    text: 'Who wrote "The Cat in the Hat"?',
    options: ['Dr. Seuss', 'Roald Dahl', 'Shel Silverstein', 'E. B. White'],
    correctIndex: 0,
  },
  {
    id: 't051', category: 'Science', difficulty: 'medium',
    text: 'What is the largest organ of the human body?',
    options: ['Skin', 'Liver', 'Heart', 'Lung'],
    correctIndex: 0,
  },
  {
    id: 't052', category: 'Geography', difficulty: 'hard',
    text: 'Which country has the most time zones including overseas territories?',
    options: ['France', 'Russia', 'United States', 'China'],
    correctIndex: 0,
  },
  {
    id: 't053', category: 'History', difficulty: 'medium',
    text: 'The Magna Carta was signed in which year?',
    options: ['1215', '1066', '1492', '1776'],
    correctIndex: 0,
  },
  {
    id: 't054', category: 'Pop Culture', difficulty: 'easy',
    text: 'What is the name of Mario\'s brother?',
    options: ['Luigi', 'Wario', 'Yoshi', 'Toad'],
    correctIndex: 0,
  },
  {
    id: 't055', category: 'Science', difficulty: 'easy',
    text: 'What do bees collect from flowers to make honey?',
    options: ['Nectar', 'Pollen', 'Sap', 'Seeds'],
    correctIndex: 0,
  },
  {
    id: 't056', category: 'Music', difficulty: 'hard',
    text: 'Which composer wrote "The Four Seasons"?',
    options: ['Antonio Vivaldi', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven'],
    correctIndex: 0,
  },
  {
    id: 't057', category: 'Language', difficulty: 'easy',
    text: 'Which punctuation mark ends an interrogative sentence?',
    options: ['Question mark', 'Period', 'Comma', 'Colon'],
    correctIndex: 0,
  },
  {
    id: 't058', category: 'Geography', difficulty: 'medium',
    text: 'Which US state is known as the Sunshine State?',
    options: ['Florida', 'California', 'Arizona', 'Hawaii'],
    correctIndex: 0,
  },
  {
    id: 't059', category: 'Science', difficulty: 'medium',
    text: 'What is the chemical symbol for sodium?',
    options: ['Na', 'S', 'So', 'N'],
    correctIndex: 0,
  },
  {
    id: 't060', category: 'History', difficulty: 'hard',
    text: 'Which civilization built Machu Picchu?',
    options: ['Inca', 'Maya', 'Aztec', 'Olmec'],
    correctIndex: 0,
  },
  {
    id: 't061', category: 'Food', difficulty: 'medium',
    text: 'What type of pasta is shaped like small rice grains?',
    options: ['Orzo', 'Penne', 'Fusilli', 'Rigatoni'],
    correctIndex: 0,
  },
  {
    id: 't062', category: 'Sports', difficulty: 'hard',
    text: 'In bowling, what is three strikes in a row called?',
    options: ['Turkey', 'Hat trick', 'Triple', 'Clean frame'],
    correctIndex: 0,
  },
  {
    id: 't063', category: 'Books', difficulty: 'medium',
    text: 'Which novel begins with "Call me Ishmael"?',
    options: ['Moby-Dick', 'The Old Man and the Sea', 'Treasure Island', 'The Odyssey'],
    correctIndex: 0,
  },
  {
    id: 't064', category: 'Science', difficulty: 'hard',
    text: 'What is the study of fungi called?',
    options: ['Mycology', 'Botany', 'Zoology', 'Ecology'],
    correctIndex: 0,
  },
  {
    id: 't065', category: 'Geography', difficulty: 'easy',
    text: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    correctIndex: 0,
  },
  {
    id: 't066', category: 'Pop Culture', difficulty: 'medium',
    text: 'Which animated series is set in the town of Springfield?',
    options: ['The Simpsons', 'Family Guy', 'Bob\'s Burgers', 'South Park'],
    correctIndex: 0,
  },
  {
    id: 't067', category: 'Science', difficulty: 'medium',
    text: 'What is the nearest star to Earth after the Sun?',
    options: ['Proxima Centauri', 'Sirius', 'Alpha Centauri A', 'Barnard\'s Star'],
    correctIndex: 0,
  },
  {
    id: 't068', category: 'History', difficulty: 'medium',
    text: 'Who was the first woman to fly solo across the Atlantic Ocean?',
    options: ['Amelia Earhart', 'Bessie Coleman', 'Harriet Quimby', 'Jacqueline Cochran'],
    correctIndex: 0,
  },
  {
    id: 't069', category: 'Language', difficulty: 'hard',
    text: 'What is the term for a word that is spelled the same backward and forward?',
    options: ['Palindrome', 'Anagram', 'Homonym', 'Acronym'],
    correctIndex: 0,
  },
  {
    id: 't070', category: 'Geography', difficulty: 'hard',
    text: 'Which African country was formerly known as Abyssinia?',
    options: ['Ethiopia', 'Eritrea', 'Sudan', 'Somalia'],
    correctIndex: 0,
  },
]

// ── Utility ───────────────────────────────────────────────────────────────────

export function shuffleArray<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export function getRandomQuiplashPrompts(count: number, usedIds: Set<string> = new Set()): QuiplashPromptDef[] {
  const available = QUIPLASH_PROMPTS.filter(p => !usedIds.has(p.id) && p.category !== 'finallash')
  return shuffleArray(available).slice(0, count)
}

export function getRandomFinalLashPrompt(usedIds: Set<string> = new Set()): QuiplashPromptDef {
  const finalLash = QUIPLASH_PROMPTS.filter(p => p.category === 'finallash' && !usedIds.has(p.id))
  const shuffled = shuffleArray(finalLash)
  return shuffled[0] ?? QUIPLASH_PROMPTS.filter(p => p.category === 'finallash')[0]
}

export function getRandomFibbagePrompts(count: number): typeof FIBBAGE_PROMPTS {
  return shuffleArray(FIBBAGE_PROMPTS).slice(0, count)
}

export function getRandomTriviaQuestions(count: number): TriviaQuestion[] {
  return shuffleArray(TRIVIA_QUESTIONS).slice(0, count)
}
